// frontend/src/features/job/JobFinishTab.tsx
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import {
  AlertTriangle,
  ArrowDown,
  ArrowUp,
  CheckCircle,
  XCircle,
  type LucideIcon,
} from 'lucide-react'
import { toast } from 'sonner'

import {
  apiErrorMessage,
  jobJobsCostsSummaryRetrieveOptions,
  jobJobsFinishPartialUpdateMutation,
  jobJobsFinishRetrieveOptions,
  jobJobsFinishRetrieveQueryKey,
  jobJobsInvoicesRetrieveQueryKey,
} from '@/api'
import type { CostSetSummaryOut, JobCompletionChecklistOut, JobDetail } from '@/api'
import { formatCurrency, formatPercentage } from '@/lib/format'
import { JobInvoiceCard } from './JobInvoiceCard'

type ChecklistKey = keyof JobCompletionChecklistOut

const ALL_CHECKLIST_ITEMS: Array<{ key: ChecklistKey; label: string }> = [
  { key: 'foreman_signed_off', label: 'Has the supervisor signed off the job?' },
  { key: 'timesheets_collected', label: "Have you collected today's timesheet entries?" },
  { key: 'materials_checked', label: 'Are all materials used written correctly on the job sheet?' },
  { key: 'customer_called', label: 'Have you called the customer?' },
  { key: 'released', label: 'Has the job been handed over?' },
]

interface NormalizedCostSummary {
  cost: number
  rev: number
  hours: number
  profitMargin: number
}

const normalize = (summary: CostSetSummaryOut | null | undefined): NormalizedCostSummary => ({
  cost: summary?.cost ?? 0,
  rev: summary?.rev ?? 0,
  hours: summary?.hours ?? 0,
  profitMargin: summary?.profitMargin ?? 0,
})

function percentDiff(actual: number, reference: number): number {
  if (!reference) return 0
  return ((actual - reference) / reference) * 100
}

function signedPercent(value: number): string {
  return `${value > 0 ? '+' : ''}${formatPercentage(value)}`
}

const NUMBER = new Intl.NumberFormat('en-NZ', {
  minimumFractionDigits: 0,
  maximumFractionDigits: 2,
})

function DiffCell({
  value,
  diff,
  goodWhenPositive,
  format,
}: {
  value: number
  diff: number
  goodWhenPositive: boolean
  format: (value: number) => string
}) {
  const isGood = goodWhenPositive ? diff >= 0 : diff <= 0
  const Icon: LucideIcon | null = diff > 0 ? ArrowUp : diff < 0 ? ArrowDown : null
  return (
    <span className={isGood ? 'font-bold text-green-600' : 'font-bold text-red-600'}>
      {format(value)}
      {diff !== 0 && Icon && (
        <>
          <Icon className="ml-1 inline h-4 w-4 align-text-bottom" />
          <span className={isGood ? 'text-green-600' : 'text-red-600'}>{signedPercent(diff)}</span>
        </>
      )}
    </span>
  )
}

interface JobFinishTabProps {
  jobId: string
  job: JobDetail
}

/**
 * Finish Job workspace: the server-owned customer balance, invoice card,
 * completion checklist, and the estimate/quote/actual comparison. Nothing
 * here recomputes money — every figure is formatted from what the server
 * sent (ADR 0046), so invoicing and display cannot disagree.
 */
export function JobFinishTab({ jobId, job }: JobFinishTabProps) {
  const queryClient = useQueryClient()
  const finishQuery = useQuery(jobJobsFinishRetrieveOptions({ path: { job_id: jobId } }))
  const costsQuery = useQuery(jobJobsCostsSummaryRetrieveOptions({ path: { job_id: jobId } }))
  const checklistSave = useMutation(jobJobsFinishPartialUpdateMutation())

  const summary = finishQuery.data?.summary ?? null
  const checklist = finishQuery.data?.checklist ?? null
  const loading = finishQuery.isPending || costsQuery.isPending
  const loadError = finishQuery.isError || costsQuery.isError

  const estimate = normalize(costsQuery.data?.estimate)
  const quote = normalize(costsQuery.data?.quote)
  const actual = normalize(costsQuery.data?.actual)
  const hasValidQuoteData = Boolean(costsQuery.data?.quote && (quote.cost > 0 || quote.rev > 0))

  const isTimeMaterials = job.pricing_methodology === 'time_materials'
  const showQuoteColumn = !isTimeMaterials && (hasValidQuoteData || quote.cost > 0 || quote.rev > 0)

  // Timesheets only exist to invoice on a T&M job; a quoted job is never asked.
  const checklistItems = isTimeMaterials
    ? ALL_CHECKLIST_ITEMS
    : ALL_CHECKLIST_ITEMS.filter((item) => item.key !== 'timesheets_collected')

  const jobValueLabel =
    job.pricing_methodology === 'fixed_price'
      ? 'Quote total (excl GST)'
      : 'Job value to date (excl GST)'

  // Invoicing changed the balance, so the server is re-read rather than the
  // figure adjusted locally; a failed reload surfaces as the query's error
  // state instead of leaving the pre-invoice figure on screen looking current.
  const reloadFinishData = () => {
    void queryClient.invalidateQueries({
      queryKey: jobJobsFinishRetrieveQueryKey({ path: { job_id: jobId } }),
    })
    void queryClient.invalidateQueries({
      queryKey: jobJobsInvoicesRetrieveQueryKey({ path: { job_id: jobId } }),
    })
  }

  const toggleChecklist = (key: ChecklistKey, checked: boolean) => {
    checklistSave.mutate(
      { path: { job_id: jobId }, body: { [key]: checked } },
      {
        onSuccess: (response) => {
          queryClient.setQueryData(
            jobJobsFinishRetrieveQueryKey({ path: { job_id: jobId } }),
            response,
          )
        },
        onError: (error) => {
          toast.error(apiErrorMessage(error, 'Failed to save checklist'))
        },
      },
    )
  }

  // --- KAN-222 labour hours ---
  const labourBudgetHours =
    job.pricing_methodology === 'fixed_price' && hasValidQuoteData ? quote.hours : estimate.hours
  const labourRemainingHours = Math.max(labourBudgetHours - actual.hours, 0)
  const labourOverrunHours = Math.max(actual.hours - labourBudgetHours, 0)

  const costRef = isTimeMaterials || !showQuoteColumn ? estimate.cost : quote.cost
  const revRef = isTimeMaterials || !showQuoteColumn ? estimate.rev : quote.rev
  const pmRef = isTimeMaterials || !showQuoteColumn ? estimate.profitMargin : quote.profitMargin
  const hoursRef = isTimeMaterials || !showQuoteColumn ? estimate.hours : quote.hours

  const costDiff = percentDiff(actual.cost, costRef)
  const revenueDiff = percentDiff(actual.rev, revRef)
  const profitDiff = percentDiff(actual.profitMargin, pmRef)
  const hoursDiff = percentDiff(actual.hours, hoursRef)

  const quoteDeviation = Math.abs(percentDiff(actual.cost, quote.cost))
  const quoteStatus: 'nodata' | 'good' | 'amber' | 'red' =
    !showQuoteColumn || !hasValidQuoteData || quote.cost === 0
      ? 'nodata'
      : quoteDeviation <= 20
        ? 'good'
        : quoteDeviation <= 40
          ? 'amber'
          : 'red'
  const QuoteAccuracyIcon =
    quoteStatus === 'good' ? CheckCircle : quoteStatus === 'amber' ? AlertTriangle : XCircle
  const quoteAccuracyClass =
    quoteStatus === 'good'
      ? 'text-green-600'
      : quoteStatus === 'amber'
        ? 'text-yellow-600'
        : quoteStatus === 'red'
          ? 'text-red-600'
          : 'text-gray-500'

  return (
    <div className="space-y-6 p-6">
      <div className="flex items-center justify-between rounded-lg border border-gray-200 bg-white p-4">
        <div>
          <h2 className="text-lg font-semibold text-gray-900">Finish Job</h2>
          <p className="text-sm text-gray-500">
            {isTimeMaterials
              ? 'Compare Estimate and Actual cost sets for this Time & Materials job'
              : !showQuoteColumn
                ? 'Compare Estimate and Actual cost sets for this job (no quote available)'
                : 'Compare Estimate, Quote, and Actual cost sets with visual performance indicators'}
          </p>
        </div>
      </div>

      {loading ? (
        <div className="flex items-center justify-center py-12">
          <div className="text-center">
            <div className="mx-auto mb-2 h-8 w-8 animate-spin rounded-full border-b-2 border-blue-600" />
            <p className="text-gray-500">Loading job financials...</p>
          </div>
        </div>
      ) : loadError || !summary || !checklist ? (
        // No fabricated placeholder: a failed load must not render as a
        // settled $0 job.
        <div
          data-automation-id="JobFinishTab-load-error"
          className="rounded-lg border border-red-200 bg-white p-6 text-center"
        >
          <p className="font-medium text-red-700">Could not load this job&apos;s financials.</p>
          <p className="mt-1 text-sm text-slate-600">Reload the page.</p>
        </div>
      ) : (
        <>
          <div className="grid grid-cols-1 items-start gap-4 lg:grid-cols-[1fr_360px]">
            <section
              data-automation-id="JobFinishTab-balance"
              className="rounded-xl border border-slate-200 bg-white p-4"
            >
              <h3 className="text-base font-semibold text-gray-900">Customer balance</h3>

              <dl className="mt-3 space-y-1.5 text-sm">
                <div className="flex justify-between">
                  <dt className="text-slate-600">{jobValueLabel}</dt>
                  <dd className="font-medium tabular-nums">
                    {formatCurrency(Number(summary.job_value_excl_gst))}
                  </dd>
                </div>
                <div className="flex justify-between">
                  <dt className="text-slate-600">Already invoiced (excl GST)</dt>
                  <dd className="font-medium tabular-nums">
                    {formatCurrency(Number(summary.valid_invoiced_excl_gst))}
                  </dd>
                </div>
                <div className="flex justify-between border-t border-slate-200 pt-1.5">
                  <dt className="text-slate-600">Still to invoice (excl GST)</dt>
                  <dd
                    data-automation-id="JobFinishTab-remaining-excl-gst"
                    className="font-medium tabular-nums"
                  >
                    {formatCurrency(Number(summary.remaining_to_invoice_excl_gst))}
                  </dd>
                </div>
                <div className="flex justify-between">
                  <dt className="text-slate-600">GST</dt>
                  <dd
                    data-automation-id="JobFinishTab-remaining-gst"
                    className="font-medium tabular-nums"
                  >
                    {formatCurrency(Number(summary.remaining_gst))}
                  </dd>
                </div>
                {Number(summary.outstanding_invoiced_incl_gst) > 0 && (
                  <div className="flex justify-between">
                    <dt className="text-slate-600">Unpaid invoices (incl GST)</dt>
                    <dd
                      data-automation-id="JobFinishTab-outstanding-incl-gst"
                      className="font-medium tabular-nums"
                    >
                      {formatCurrency(Number(summary.outstanding_invoiced_incl_gst))}
                    </dd>
                  </div>
                )}
                <div className="mt-1 flex items-baseline justify-between border-t-2 border-slate-300 pt-2">
                  <dt className="font-semibold text-slate-900">Total to pay</dt>
                  <dd
                    data-automation-id="JobFinishTab-total-to-pay"
                    className="text-2xl font-bold tabular-nums text-emerald-700"
                  >
                    {formatCurrency(Number(summary.total_to_pay_incl_gst))}
                  </dd>
                </div>
              </dl>

              {Number(summary.over_invoiced_excl_gst) > 0 && (
                <div
                  data-automation-id="JobFinishTab-over-invoiced"
                  className="mt-3 rounded-md border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900"
                >
                  <strong>
                    Job appears over-invoiced by{' '}
                    {formatCurrency(Number(summary.over_invoiced_excl_gst))}
                  </strong>{' '}
                  (excl GST). The job value may be out of date, or invoicing may need correcting.
                </div>
              )}
            </section>

            <JobInvoiceCard
              jobId={jobId}
              pricingMethodology={job.pricing_methodology}
              remainingToInvoice={Number(summary.remaining_to_invoice_excl_gst)}
              jobStatus={job.job_status}
              paid={job.paid}
              onInvoicesChanged={reloadFinishData}
            />
          </div>

          <section
            data-automation-id="JobFinishTab-checklist"
            className="rounded-xl border border-slate-200 bg-white p-4"
          >
            <h3 className="text-base font-semibold text-gray-900">Completion checklist</h3>
            <p className="mb-3 text-xs text-slate-500">Self-checklist.</p>

            <div className="space-y-2">
              {checklistItems.map((item) => (
                <label key={item.key} className="flex cursor-pointer items-start gap-2 text-sm">
                  <input
                    type="checkbox"
                    checked={checklist[item.key]}
                    data-automation-id={`JobFinishTab-checklist-${item.key}`}
                    className="mt-0.5 h-4 w-4 rounded border-slate-300"
                    disabled={checklistSave.isPending}
                    onChange={(event) => toggleChecklist(item.key, event.target.checked)}
                  />
                  <span className="text-slate-800">{item.label}</span>
                </label>
              ))}
            </div>
          </section>

          <div
            data-automation-id="JobFinishTab-labour-hours"
            className="grid grid-cols-1 gap-3 text-sm sm:grid-cols-3"
          >
            <div className="rounded-lg border border-slate-200 bg-white p-3">
              <div className="text-[11px] tracking-wide text-slate-500 uppercase">
                Labour budget
              </div>
              <div
                data-automation-id="JobFinishTab-labour-budget"
                className="text-lg font-semibold tabular-nums text-slate-900"
              >
                {NUMBER.format(labourBudgetHours)}
              </div>
            </div>
            <div className="rounded-lg border border-slate-200 bg-white p-3">
              <div className="text-[11px] tracking-wide text-slate-500 uppercase">Hours used</div>
              <div
                data-automation-id="JobFinishTab-labour-used"
                className="text-lg font-semibold tabular-nums text-slate-900"
              >
                {NUMBER.format(actual.hours)}
              </div>
            </div>
            <div
              className={`rounded-lg border bg-white p-3 ${
                labourOverrunHours > 0 ? 'border-red-200 bg-red-50' : 'border-slate-200'
              }`}
            >
              <div className="text-[11px] tracking-wide text-slate-500 uppercase">
                {labourOverrunHours > 0 ? 'Overrun' : 'Hours remaining'}
              </div>
              <div
                data-automation-id="JobFinishTab-labour-remaining"
                className={`text-lg font-semibold tabular-nums ${
                  labourOverrunHours > 0 ? 'text-red-700' : 'text-slate-900'
                }`}
              >
                {NUMBER.format(labourOverrunHours > 0 ? labourOverrunHours : labourRemainingHours)}
              </div>
            </div>
          </div>

          <div className="overflow-x-auto">
            <table className="min-w-full rounded-lg border border-gray-200 bg-white text-sm">
              <thead>
                <tr className="bg-gray-50">
                  <th className="px-4 py-3 text-left font-semibold text-gray-700">Metric</th>
                  <th className="px-4 py-3 text-center font-semibold text-blue-700">Estimate</th>
                  {showQuoteColumn && (
                    <th className="px-4 py-3 text-center font-semibold text-green-700">Quote</th>
                  )}
                  <th className="px-4 py-3 text-center font-semibold text-orange-700">Actual</th>
                </tr>
              </thead>
              <tbody className="[&_td]:border-b [&_td]:border-gray-200 [&_th]:border-b [&_th]:border-gray-200">
                <tr>
                  <td className="px-4 py-2 font-medium">Total Cost</td>
                  <td className="px-4 py-2 text-center">{formatCurrency(estimate.cost)}</td>
                  {showQuoteColumn && (
                    <td className="px-4 py-2 text-center">{formatCurrency(quote.cost)}</td>
                  )}
                  <td className="px-4 py-2 text-center">
                    <DiffCell
                      value={actual.cost}
                      diff={costDiff}
                      goodWhenPositive={false}
                      format={formatCurrency}
                    />
                  </td>
                </tr>
                <tr>
                  <td className="px-4 py-2 font-medium">Total Revenue</td>
                  <td className="px-4 py-2 text-center">{formatCurrency(estimate.rev)}</td>
                  {showQuoteColumn && (
                    <td className="px-4 py-2 text-center">{formatCurrency(quote.rev)}</td>
                  )}
                  <td className="px-4 py-2 text-center">
                    <DiffCell
                      value={actual.rev}
                      diff={revenueDiff}
                      goodWhenPositive
                      format={formatCurrency}
                    />
                  </td>
                </tr>
                <tr>
                  <td className="px-4 py-2 font-medium">Profit Margin</td>
                  <td className="px-4 py-2 text-center">
                    {formatPercentage(estimate.profitMargin)}
                  </td>
                  {showQuoteColumn && (
                    <td className="px-4 py-2 text-center">
                      {formatPercentage(quote.profitMargin)}
                    </td>
                  )}
                  <td className="px-4 py-2 text-center">
                    <DiffCell
                      value={actual.profitMargin}
                      diff={profitDiff}
                      goodWhenPositive
                      format={formatPercentage}
                    />
                  </td>
                </tr>
                <tr>
                  <td className="px-4 py-2 font-medium">Total Hours</td>
                  <td className="px-4 py-2 text-center">{NUMBER.format(estimate.hours)}</td>
                  {showQuoteColumn && (
                    <td className="px-4 py-2 text-center">{NUMBER.format(quote.hours)}</td>
                  )}
                  <td className="px-4 py-2 text-center">
                    <DiffCell
                      value={actual.hours}
                      diff={hoursDiff}
                      goodWhenPositive={false}
                      format={(value) => NUMBER.format(value)}
                    />
                  </td>
                </tr>
              </tbody>
            </table>

            {showQuoteColumn && (
              <div className="mt-6 flex flex-col gap-4 md:flex-row">
                {quoteStatus !== 'nodata' ? (
                  <div className="flex flex-1 items-center gap-3 rounded-lg border border-gray-200 bg-white p-4">
                    <QuoteAccuracyIcon className={`h-8 w-8 ${quoteAccuracyClass}`} />
                    <div>
                      <div className="font-semibold text-gray-900">Quote Accuracy</div>
                      <div className={`text-lg font-bold ${quoteAccuracyClass}`}>
                        {signedPercent(percentDiff(actual.cost, quote.cost))}
                      </div>
                      <div className="text-xs text-gray-500">
                        Deviation of actual cost from quoted cost
                      </div>
                    </div>
                  </div>
                ) : (
                  <div className="flex flex-1 items-center gap-3 rounded-lg border border-gray-200 bg-gray-50 p-4">
                    <div className="flex h-8 w-8 items-center justify-center rounded-full bg-gray-300">
                      <span className="text-sm text-gray-500">?</span>
                    </div>
                    <div>
                      <div className="font-semibold text-gray-500">Quote Accuracy</div>
                      <div className="text-sm text-gray-500">
                        {!quote.cost ? 'No quote data available' : 'No actual data available'}
                      </div>
                    </div>
                  </div>
                )}
              </div>
            )}
          </div>
        </>
      )}
    </div>
  )
}

// frontend/src/components/job/JobFinishTab.vue
<template>
  <div class="space-y-6">
    <div class="flex items-center justify-between bg-white p-4 rounded-lg border border-gray-200">
      <div>
        <h2 class="text-lg font-semibold text-gray-900">Finish Job</h2>
        <p class="text-sm text-gray-500">
          <span v-if="props.pricingMethodology === 'time_materials'">
            Compare Estimate and Actual cost sets for this Time & Materials job
          </span>
          <span v-else-if="!showQuoteColumn">
            Compare Estimate and Actual cost sets for this job (no quote available)
          </span>
          <span v-else>
            Compare Estimate, Quote, and Actual cost sets with visual performance indicators
          </span>
        </p>
      </div>
    </div>

    <div v-if="loading" class="flex items-center justify-center py-12">
      <div class="text-center">
        <div
          class="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600 mx-auto mb-2"
        ></div>
        <p class="text-gray-500">Loading job financials...</p>
      </div>
    </div>

    <div
      v-else-if="loadError"
      data-automation-id="JobFinishTab-load-error"
      class="bg-white rounded-lg border border-red-200 p-6 text-center"
    >
      <p class="text-red-700 font-medium">Could not load this job's financials.</p>
      <p class="text-sm text-slate-600 mt-1">Reload the page.</p>
    </div>

    <template v-else-if="summary">
      <div class="grid grid-cols-1 lg:grid-cols-[1fr_360px] gap-4 items-start">
        <section
          data-automation-id="JobFinishTab-balance"
          class="bg-white rounded-xl border border-slate-200 p-4"
        >
          <h3 class="text-base font-semibold text-gray-900">Customer balance</h3>

          <dl class="space-y-1.5 text-sm mt-3">
            <div class="flex justify-between">
              <dt class="text-slate-600">{{ jobValueLabel }}</dt>
              <dd class="tabular-nums font-medium">
                {{ formatCurrency(summary.job_value_excl_gst) }}
              </dd>
            </div>
            <div class="flex justify-between">
              <dt class="text-slate-600">Already invoiced (excl GST)</dt>
              <dd class="tabular-nums font-medium">
                {{ formatCurrency(summary.valid_invoiced_excl_gst) }}
              </dd>
            </div>
            <div class="border-t border-slate-200 pt-1.5 flex justify-between">
              <dt class="text-slate-600">Still to invoice (excl GST)</dt>
              <dd
                data-automation-id="JobFinishTab-remaining-excl-gst"
                class="tabular-nums font-medium"
              >
                {{ formatCurrency(summary.remaining_to_invoice_excl_gst) }}
              </dd>
            </div>
            <div class="flex justify-between">
              <dt class="text-slate-600">GST</dt>
              <dd data-automation-id="JobFinishTab-remaining-gst" class="tabular-nums font-medium">
                {{ formatCurrency(summary.remaining_gst) }}
              </dd>
            </div>
            <div v-if="summary.outstanding_invoiced_incl_gst > 0" class="flex justify-between">
              <dt class="text-slate-600">Unpaid invoices (incl GST)</dt>
              <dd
                data-automation-id="JobFinishTab-outstanding-incl-gst"
                class="tabular-nums font-medium"
              >
                {{ formatCurrency(summary.outstanding_invoiced_incl_gst) }}
              </dd>
            </div>
            <div class="border-t-2 border-slate-300 pt-2 mt-1 flex justify-between items-baseline">
              <dt class="font-semibold text-slate-900">Total to pay</dt>
              <dd
                data-automation-id="JobFinishTab-total-to-pay"
                class="tabular-nums text-2xl font-bold text-emerald-700"
              >
                {{ formatCurrency(summary.total_to_pay_incl_gst) }}
              </dd>
            </div>
          </dl>

          <div
            v-if="summary.over_invoiced_excl_gst > 0"
            data-automation-id="JobFinishTab-over-invoiced"
            class="mt-3 rounded-md bg-amber-50 border border-amber-200 p-3 text-sm text-amber-900"
          >
            <strong
              >Job appears over-invoiced by
              {{ formatCurrency(summary.over_invoiced_excl_gst) }}</strong
            >
            (excl GST). The job value may be out of date, or invoicing may need correcting.
          </div>
        </section>

        <JobInvoiceCard
          :job-id="props.jobId"
          :pricing-methodology="props.pricingMethodology"
          :remaining-to-invoice="summary.remaining_to_invoice_excl_gst"
          :job-status="props.jobStatus"
          :paid="props.paid"
          @invoices-changed="reloadFinishSummary"
        />
      </div>

      <section
        data-automation-id="JobFinishTab-checklist"
        class="bg-white rounded-xl border border-slate-200 p-4"
      >
        <h3 class="text-base font-semibold text-gray-900">Completion checklist</h3>
        <p class="text-xs text-slate-500 mb-3">Self-checklist.</p>

        <div class="space-y-2">
          <label
            v-for="item in checklistItems"
            :key="item.key"
            class="flex items-start gap-2 text-sm cursor-pointer"
          >
            <input
              v-model="checklist[item.key]"
              type="checkbox"
              :data-automation-id="`JobFinishTab-checklist-${item.key}`"
              class="mt-0.5 h-4 w-4 rounded border-slate-300"
              :disabled="savingChecklistKey !== null"
              @change="onChecklistToggle(item.key)"
            />
            <span class="text-slate-800">{{ item.label }}</span>
          </label>
        </div>
      </section>
    </template>

    <div
      v-if="summary && !loadError"
      data-automation-id="JobFinishTab-labour-hours"
      class="grid grid-cols-1 sm:grid-cols-3 gap-3 text-sm"
    >
      <div class="rounded-lg border border-slate-200 bg-white p-3">
        <div class="text-[11px] uppercase tracking-wide text-slate-500">Labour budget</div>
        <div
          data-automation-id="JobFinishTab-labour-budget"
          class="text-lg font-semibold tabular-nums text-slate-900"
        >
          {{ formatNumber(labourBudgetHours) }}
        </div>
      </div>
      <div class="rounded-lg border border-slate-200 bg-white p-3">
        <div class="text-[11px] uppercase tracking-wide text-slate-500">Hours used</div>
        <div
          data-automation-id="JobFinishTab-labour-used"
          class="text-lg font-semibold tabular-nums text-slate-900"
        >
          {{ formatNumber(actual.hours) }}
        </div>
      </div>
      <div
        class="rounded-lg border bg-white p-3"
        :class="labourOverrunHours > 0 ? 'border-red-200 bg-red-50' : 'border-slate-200'"
      >
        <div class="text-[11px] uppercase tracking-wide text-slate-500">
          {{ labourOverrunHours > 0 ? 'Overrun' : 'Hours remaining' }}
        </div>
        <div
          data-automation-id="JobFinishTab-labour-remaining"
          class="text-lg font-semibold tabular-nums"
          :class="labourOverrunHours > 0 ? 'text-red-700' : 'text-slate-900'"
        >
          {{ formatNumber(labourOverrunHours > 0 ? labourOverrunHours : labourRemainingHours) }}
        </div>
      </div>
    </div>

    <div v-if="summary && !loadError" class="overflow-x-auto">
      <table class="min-w-full bg-white rounded-lg border border-gray-200 text-sm">
        <thead>
          <tr class="bg-gray-50">
            <th class="py-3 px-4 text-left font-semibold text-gray-700">Metric</th>
            <th class="py-3 px-4 text-center font-semibold text-blue-700">Estimate</th>
            <th v-if="showQuoteColumn" class="py-3 px-4 text-center font-semibold text-green-700">
              Quote
            </th>
            <th class="py-3 px-4 text-center font-semibold text-orange-700">Actual</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td class="py-2 px-4 font-medium">Total Cost</td>
            <td class="py-2 px-4 text-center">{{ formatCurrency(estimate.cost) }}</td>
            <td v-if="showQuoteColumn" class="py-2 px-4 text-center">
              {{ formatCurrency(quote.cost) }}
            </td>
            <td class="py-2 px-4 text-center">
              <span :class="costClass">
                {{ formatCurrency(actual.cost) }}
                <span v-if="costDiff !== 0">
                  <component :is="costIcon" class="inline w-4 h-4 align-text-bottom ml-1" />
                  <span :class="costDiff > 0 ? 'text-red-600' : 'text-green-600'">
                    {{ formatPercent(costDiff) }}
                  </span>
                </span>
              </span>
            </td>
          </tr>
          <tr>
            <td class="py-2 px-4 font-medium">Total Revenue</td>
            <td class="py-2 px-4 text-center">{{ formatCurrency(estimate.rev) }}</td>
            <td v-if="showQuoteColumn" class="py-2 px-4 text-center">
              {{ formatCurrency(quote.rev) }}
            </td>
            <td class="py-2 px-4 text-center">
              <span :class="revenueClass">
                {{ formatCurrency(actual.rev) }}
                <span v-if="revenueDiff !== 0">
                  <component :is="revenueIcon" class="inline w-4 h-4 align-text-bottom ml-1" />
                  <span :class="revenueDiff > 0 ? 'text-green-600' : 'text-red-600'">
                    {{ formatPercent(revenueDiff) }}
                  </span>
                </span>
              </span>
            </td>
          </tr>
          <tr>
            <td class="py-2 px-4 font-medium">Profit Margin</td>
            <td class="py-2 px-4 text-center">{{ formatPercent(estimate.profitMargin) }}</td>
            <td v-if="showQuoteColumn" class="py-2 px-4 text-center">
              {{ formatPercent(quote.profitMargin) }}
            </td>
            <td class="py-2 px-4 text-center">
              <span :class="profitClass">
                {{ formatPercent(actual.profitMargin) }}
                <span v-if="profitDiff !== 0">
                  <component :is="profitIcon" class="inline w-4 h-4 align-text-bottom ml-1" />
                  <span :class="profitDiff > 0 ? 'text-green-600' : 'text-red-600'">
                    {{ formatPercent(profitDiff) }}
                  </span>
                </span>
              </span>
            </td>
          </tr>
          <tr>
            <td class="py-2 px-4 font-medium">Total Hours</td>
            <td class="py-2 px-4 text-center">{{ formatNumber(estimate.hours) }}</td>
            <td v-if="showQuoteColumn" class="py-2 px-4 text-center">
              {{ formatNumber(quote.hours) }}
            </td>
            <td class="py-2 px-4 text-center">
              <span :class="hoursClass">
                {{ formatNumber(actual.hours) }}
                <span v-if="hoursDiff !== 0">
                  <component :is="hoursIcon" class="inline w-4 h-4 align-text-bottom ml-1" />
                  <span :class="hoursDiff < 0 ? 'text-green-600' : 'text-red-600'">
                    {{ formatPercent(hoursDiff) }}
                  </span>
                </span>
              </span>
            </td>
          </tr>
        </tbody>
      </table>

      <div v-if="showQuoteColumn" class="mt-6 flex flex-col md:flex-row gap-4">
        <div
          v-if="quotePerformance.status !== 'nodata'"
          class="flex-1 bg-white rounded-lg border border-gray-200 p-4 flex items-center gap-3"
        >
          <component
            :is="quoteAccuracyIcon"
            v-if="quoteAccuracyIcon"
            class="w-8 h-8"
            :class="quoteAccuracyClass"
          />
          <div>
            <div class="font-semibold text-gray-900">Quote Accuracy</div>
            <div class="text-lg font-bold" :class="quoteAccuracyClass">
              {{ formatPercent(quoteAccuracyDisplayValue) }}
            </div>
            <div class="text-xs text-gray-500">Deviation of actual cost from quoted cost</div>
          </div>
        </div>
        <div
          v-else
          class="flex-1 bg-gray-50 rounded-lg border border-gray-200 p-4 flex items-center gap-3"
        >
          <div class="w-8 h-8 bg-gray-300 rounded-full flex items-center justify-center">
            <span class="text-gray-500 text-sm">?</span>
          </div>
          <div>
            <div class="font-semibold text-gray-500">Quote Accuracy</div>
            <div class="text-sm text-gray-500">
              {{ !quote.cost ? 'No quote data available' : 'No actual data available' }}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, ref, onMounted, reactive } from 'vue'
import { toast } from 'vue-sonner'
import { ArrowUp, ArrowDown, CheckCircle, AlertTriangle, XCircle } from 'lucide-vue-next'
import { api } from '../../api/client'
import debug from 'debug'
import JobInvoiceCard from './JobInvoiceCard.vue'
import { formatCurrency } from '@/utils/string-formatting'
import { schemas } from '../../api/generated/api'
import { z } from 'zod'

type JobCostSetSummaryOutput = z.infer<typeof schemas.JobCostSetSummary>
type NumericField<K extends keyof JobCostSetSummaryOutput> = Extract<
  JobCostSetSummaryOutput[K],
  number
>
type NormalizedCostSummary = {
  cost: NumericField<'cost'>
  rev: NumericField<'rev'>
  hours: NumericField<'hours'>
  profitMargin: number
}
type JobCostSummaryResponse = z.infer<typeof schemas.JobCostSummaryResponse>

const props = defineProps<{
  jobId: string
  pricingMethodology: string
  jobStatus?: string
  paid?: boolean
}>()

const loading = ref(true)
const hasValidQuoteData = ref(false)

const zeroSummary = (): NormalizedCostSummary => ({
  cost: 0,
  rev: 0,
  hours: 0,
  profitMargin: 0,
})

const log = debug('job:finish')

type FinishJobSummary = z.infer<typeof schemas.FinishJobSummary>
type JobCompletionChecklist = z.infer<typeof schemas.JobCompletionChecklist>
type ChecklistItemKey = keyof JobCompletionChecklist

// No fabricated placeholder: until the server answers there is no balance, and a
// failed load must not render as a settled $0 job.
const summary = ref<FinishJobSummary | null>(null)
const loadError = ref(false)
const checklist = reactive<JobCompletionChecklist>({
  foreman_signed_off: false,
  timesheets_collected: false,
  materials_checked: false,
  customer_called: false,
  released: false,
})
const savingChecklistKey = ref<ChecklistItemKey | null>(null)

const allChecklistItems: Array<{ key: ChecklistItemKey; label: string }> = [
  { key: 'foreman_signed_off', label: 'Has the supervisor signed off the job?' },
  { key: 'timesheets_collected', label: "Have you collected today's timesheet entries?" },
  { key: 'materials_checked', label: 'Are all materials used written correctly on the job sheet?' },
  { key: 'customer_called', label: 'Have you called the customer?' },
  { key: 'released', label: 'Has the job been handed over?' },
]

// Timesheets only exist to invoice on a T&M job; a quoted job is never asked.
const checklistItems = computed(() =>
  props.pricingMethodology === 'time_materials'
    ? allChecklistItems
    : allChecklistItems.filter((item) => item.key !== 'timesheets_collected'),
)

const jobValueLabel = computed(() =>
  props.pricingMethodology === 'fixed_price'
    ? 'Quote total (excl GST)'
    : 'Job value to date (excl GST)',
)

const estimate = reactive<NormalizedCostSummary>(zeroSummary())
const quote = reactive<NormalizedCostSummary>(zeroSummary())
const actual = reactive<NormalizedCostSummary>(zeroSummary())

const ensureSummary = (s?: JobCostSetSummaryOutput | null): NormalizedCostSummary => ({
  cost: s?.cost ?? 0,
  rev: s?.rev ?? 0,
  hours: s?.hours ?? 0,
  profitMargin: s?.profitMargin ?? 0,
})

async function loadFinishSummary() {
  const response = await api.job_jobs_finish_retrieve({ params: { job_id: props.jobId } })
  summary.value = response.summary
  Object.assign(checklist, response.checklist)
}

async function loadCostSummary() {
  const resp: JobCostSummaryResponse = await api.job_jobs_costs_summary_retrieve({
    params: { job_id: props.jobId },
  })

  Object.assign(estimate, ensureSummary(resp.estimate))
  Object.assign(quote, ensureSummary(resp.quote))
  Object.assign(actual, ensureSummary(resp.actual))

  hasValidQuoteData.value =
    !!resp.quote && ((resp.quote.cost ?? 0) > 0 || (resp.quote.rev ?? 0) > 0)
}

async function loadAll() {
  loading.value = true
  loadError.value = false
  try {
    await Promise.all([loadFinishSummary(), loadCostSummary()])
  } catch (error) {
    log('Failed to load Finish Job data: %o', error)
    toast.error('Failed to load job financials')
    // Leave summary null and say so. Showing zeros here would tell staff a job
    // is settled when we simply could not read it.
    summary.value = null
    loadError.value = true
  } finally {
    loading.value = false
  }
}

onMounted(loadAll)

// Invoicing changed the balance, so a failed reload must say so rather than
// leave the pre-invoice figure on screen looking current.
async function reloadFinishSummary() {
  try {
    await loadFinishSummary()
  } catch (error) {
    log('Failed to reload Finish Job balance: %o', error)
    summary.value = null
    loadError.value = true
    toast.error('Invoice saved, but the balance could not be refreshed. Reload the job.')
  }
}

// v-model has already applied the new value optimistically; this persists it and
// puts it back if the server refuses, so a tick never survives a failed save.
async function onChecklistToggle(key: ChecklistItemKey) {
  const checked = checklist[key]
  savingChecklistKey.value = key
  try {
    const response = await api.job_jobs_finish_partial_update(
      { [key]: checked },
      { params: { job_id: props.jobId } },
    )
    Object.assign(checklist, response.checklist)
  } catch (error) {
    log('Failed to save checklist item %s: %o', key, error)
    toast.error('Failed to save checklist')
    checklist[key] = !checked
  } finally {
    savingChecklistKey.value = null
  }
}

// --- KAN-222 labour hours ---

const labourBudgetHours = computed(() =>
  props.pricingMethodology === 'fixed_price' && hasValidQuoteData.value
    ? quote.hours
    : estimate.hours,
)
const labourRemainingHours = computed(() => Math.max(labourBudgetHours.value - actual.hours, 0))
const labourOverrunHours = computed(() => Math.max(actual.hours - labourBudgetHours.value, 0))

const showQuoteColumn = computed(() => {
  if (props.pricingMethodology === 'time_materials') return false
  return hasValidQuoteData.value || quote.cost > 0 || quote.rev > 0
})

function percentDiff(actualNum: number, refNum: number): number {
  if (!refNum) return 0
  return ((actualNum - refNum) / refNum) * 100
}

const costRef = computed(() =>
  props.pricingMethodology === 'time_materials' || !showQuoteColumn.value
    ? estimate.cost
    : quote.cost,
)
const revRef = computed(() =>
  props.pricingMethodology === 'time_materials' || !showQuoteColumn.value
    ? estimate.rev
    : quote.rev,
)
const pmRef = computed(() =>
  props.pricingMethodology === 'time_materials' || !showQuoteColumn.value
    ? estimate.profitMargin
    : quote.profitMargin,
)
const hoursRef = computed(() =>
  props.pricingMethodology === 'time_materials' || !showQuoteColumn.value
    ? estimate.hours
    : quote.hours,
)

const costDiff = computed(() => percentDiff(actual.cost, costRef.value))
const revenueDiff = computed(() => percentDiff(actual.rev, revRef.value))
const profitDiff = computed(() => percentDiff(actual.profitMargin, pmRef.value))
const hoursDiff = computed(() => percentDiff(actual.hours, hoursRef.value))

const costClass = computed(() =>
  costDiff.value > 0 ? 'text-red-600 font-bold' : 'text-green-600 font-bold',
)
const costIcon = computed(() =>
  costDiff.value > 0 ? ArrowUp : costDiff.value < 0 ? ArrowDown : null,
)

const revenueClass = computed(() =>
  revenueDiff.value >= 0 ? 'text-green-600 font-bold' : 'text-red-600 font-bold',
)
const revenueIcon = computed(() =>
  revenueDiff.value > 0 ? ArrowUp : revenueDiff.value < 0 ? ArrowDown : null,
)

const profitClass = computed(() =>
  profitDiff.value >= 0 ? 'text-green-600 font-bold' : 'text-red-600 font-bold',
)
const profitIcon = computed(() =>
  profitDiff.value > 0 ? ArrowUp : profitDiff.value < 0 ? ArrowDown : null,
)

const hoursClass = computed(() =>
  hoursDiff.value <= 0 ? 'text-green-600 font-bold' : 'text-red-600 font-bold',
)
const hoursIcon = computed(() =>
  hoursDiff.value < 0 ? ArrowDown : hoursDiff.value > 0 ? ArrowUp : null,
)

const quotePerformance = computed(() => {
  if (!showQuoteColumn.value || !hasValidQuoteData.value || quote.cost === 0) {
    return { status: 'nodata' as const, deviation: 0 }
  }
  const deviation = Math.abs(percentDiff(actual.cost, quote.cost))
  if (deviation <= 20) return { status: 'good' as const, deviation }
  if (deviation <= 40) return { status: 'amber' as const, deviation }
  return { status: 'red' as const, deviation }
})

const quoteAccuracyIcon = computed(() => {
  switch (quotePerformance.value.status) {
    case 'good':
      return CheckCircle
    case 'amber':
      return AlertTriangle
    case 'red':
      return XCircle
    default:
      return null
  }
})

const quoteAccuracyClass = computed(() => {
  switch (quotePerformance.value.status) {
    case 'good':
      return 'text-green-600'
    case 'amber':
      return 'text-yellow-600'
    case 'red':
      return 'text-red-600'
    default:
      return 'text-gray-500'
  }
})

const quoteAccuracyDisplayValue = computed(() => {
  if (quotePerformance.value.status === 'nodata') return 0
  return percentDiff(actual.cost, quote.cost)
})

function formatPercent(value: number): string {
  return `${value > 0 ? '+' : ''}${value.toFixed(1)}%`
}
function formatNumber(value: number): string {
  return new Intl.NumberFormat('en-US', {
    minimumFractionDigits: 0,
    maximumFractionDigits: 2,
  }).format(value)
}
</script>

<style scoped>
table {
  border-collapse: separate;
  border-spacing: 0;
}
th,
td {
  border-bottom: 1px solid #e5e7eb;
}
th:last-child,
td:last-child {
  border-right: none;
}
</style>
