// frontend/src/features/kanban/StaffAvatar.tsx
/**
 * One staff face, in the panel and on a card's avatar strip.
 *
 * The person shape is declared structurally rather than as a union of the two
 * wire types: KanbanStaffOut and KanbanJobPersonOut both already carry id,
 * display_name and icon_url, so a union would only reintroduce v1's
 * "which shape is this?" branching (StaffAvatar.vue:63-120).
 */
export interface AvatarPerson {
  id: string
  display_name: string
  icon_url: string | null
}

// v1's palette (StaffAvatar.vue:122-146), kept so a given person keeps the
// same colour across the rewrite.
const AVATAR_COLORS: readonly [string, ...string[]] = [
  '#3498db',
  '#2ecc71',
  '#e74c3c',
  '#9b59b6',
  '#f39c12',
  '#1abc9c',
  '#d35400',
  '#c0392b',
  '#8e44ad',
  '#16a085',
  '#27ae60',
  '#2980b9',
  '#f1c40f',
  '#e67e22',
  '#34495e',
]

function colorFor(displayName: string): string {
  let sum = 0
  for (let index = 0; index < displayName.length; index += 1) {
    sum += displayName.charCodeAt(index)
  }
  // The modulo is always in range; the `??` satisfies noUncheckedIndexedAccess,
  // it is not a fallback for missing data.
  return AVATAR_COLORS[Math.abs(sum) % AVATAR_COLORS.length] ?? AVATAR_COLORS[0]
}

function initialsFor(displayName: string): string {
  const words = displayName.trim().split(/\s+/).filter(Boolean)
  const first = words[0]
  if (!first) return '??'
  const last = words.length > 1 ? words[words.length - 1] : undefined
  if (last) return (first.charAt(0) + last.charAt(0)).toUpperCase()
  return first.slice(0, 2).toUpperCase().padEnd(2, first.charAt(0).toUpperCase())
}

interface StaffAvatarProps {
  person: AvatarPerson
  size?: 'small' | 'normal'
  isActive?: boolean
}

export function StaffAvatar({ person, size = 'normal', isActive = false }: StaffAvatarProps) {
  const dimensions = size === 'small' ? 'h-5 w-5 text-[0.6rem]' : 'h-10 w-10 text-sm'
  const activeRing = isActive ? 'ring-2 ring-blue-300 ring-offset-1 border-2 border-blue-500' : ''

  return (
    <div
      data-staff-id={person.id}
      title={person.display_name}
      className={`relative flex shrink-0 items-center justify-center overflow-hidden rounded-full shadow-sm ${dimensions} ${activeRing}`}
    >
      {person.icon_url ? (
        <img
          src={person.icon_url}
          alt={person.display_name}
          className="h-full w-full object-cover"
        />
      ) : (
        <div
          className="flex h-full w-full items-center justify-center font-bold text-white"
          style={{ backgroundColor: colorFor(person.display_name) }}
        >
          {initialsFor(person.display_name)}
        </div>
      )}
    </div>
  )
}

// frontend/src/components/StaffAvatar.vue
<template>
  <div
    :class="[
      'rounded-full overflow-hidden flex items-center justify-center cursor-pointer shadow-sm transition-all duration-200 relative',
      'hover:scale-110 hover:shadow-md',
      size === 'small' ? 'w-5 h-5 text-xs' : 'w-10 h-10',
      isActive
        ? 'border-2 border-blue-500 scale-110 shadow-blue-200 shadow-md ring-2 ring-blue-300 ring-offset-1'
        : '',
      isDragging ? 'opacity-80 rotate-1 scale-105 shadow-lg' : '',
      'staff-avatar-draggable',
    ]"
    :title="displayName"
    :data-staff-id="staff.id"
  >
    <img
      v-if="staff.icon_url"
      :src="staff.icon_url"
      :alt="displayName"
      class="w-full h-full object-cover"
    />
    <div
      v-else
      class="w-full h-full flex items-center justify-center text-white font-bold"
      :class="size === 'small' ? 'text-xs' : 'text-sm'"
      :style="{ backgroundColor: backgroundColor }"
    >
      {{ getInitials(staff) }}
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { schemas } from '@/api/generated/api'
import { z } from 'zod'

type Staff = z.infer<typeof schemas.Staff>
type KanbanJobPerson = z.infer<typeof schemas.KanbanJobPerson>

// Union type to handle both Staff and KanbanJobPerson
// This is needed due to the utilisation of StaffAvatar in both StaffPanel and KanbanColumn (through JobCard)
type StaffOrKanbanPerson = Staff | KanbanJobPerson

const props = withDefaults(
  defineProps<{
    staff: StaffOrKanbanPerson
    size?: 'normal' | 'small' | 'large'
    isActive?: boolean
    isDragging?: boolean
  }>(),
  {
    size: 'normal',
    isActive: false,
    isDragging: false,
  },
)

defineEmits<{
  click: []
}>()

const displayName = computed((): string => {
  // For KanbanJobPerson, use display_name directly
  if ('display_name' in props.staff && (props.staff as KanbanJobPerson).display_name) {
    return (props.staff as KanbanJobPerson).display_name
  }

  // For Staff objects, construct display name from first_name and last_name
  if ('first_name' in props.staff && 'last_name' in props.staff) {
    const staff = props.staff as Staff
    const firstName = staff.first_name || ''
    const lastName = staff.last_name || ''
    const fullName = `${firstName} ${lastName}`.trim()
    return fullName || staff.email || 'Unknown'
  }

  return 'Unknown'
})

const getInitials = (staff: StaffOrKanbanPerson): string => {
  // For KanbanJobPerson, use display_name
  if ('display_name' in staff && (staff as KanbanJobPerson).display_name) {
    const displayName = (staff as KanbanJobPerson).display_name
    const words = displayName.trim().split(/\s+/)
    if (words.length >= 2) {
      return words[0].charAt(0).toUpperCase() + words[words.length - 1].charAt(0).toUpperCase()
    } else if (words.length === 1 && words[0].length >= 2) {
      return words[0].substring(0, 2).toUpperCase()
    } else if (words[0].length === 1) {
      return words[0].charAt(0).toUpperCase() + words[0].charAt(0).toUpperCase()
    }
  }

  // For full Staff object, try first_name/last_name first
  if ('first_name' in staff && 'last_name' in staff) {
    const staffObj = staff as Staff
    const firstInitial = staffObj.first_name?.charAt(0)?.toUpperCase() || ''
    const lastInitial = staffObj.last_name?.charAt(0)?.toUpperCase() || ''

    if (firstInitial || lastInitial) {
      return firstInitial + lastInitial
    }
  }

  // Fallback to display_name for KanbanJobPerson objects
  if ('display_name' in staff && (staff as KanbanJobPerson).display_name) {
    const displayName = (staff as KanbanJobPerson).display_name
    const words = displayName.trim().split(/\s+/)
    if (words.length >= 2) {
      return words[0].charAt(0).toUpperCase() + words[words.length - 1].charAt(0).toUpperCase()
    } else if (words.length === 1 && words[0].length >= 2) {
      return words[0].substring(0, 2).toUpperCase()
    } else if (words[0].length === 1) {
      return words[0].charAt(0).toUpperCase() + words[0].charAt(0).toUpperCase()
    }
  }

  return '??'
}

const backgroundColor = computed(() => {
  const predefinedColors = [
    '#3498db',
    '#2ecc71',
    '#e74c3c',
    '#9b59b6',
    '#f39c12',
    '#1abc9c',
    '#d35400',
    '#c0392b',
    '#8e44ad',
    '#16a085',
    '#27ae60',
    '#2980b9',
    '#f1c40f',
    '#e67e22',
    '#34495e',
  ]

  const name = displayName.value
  const colorIndex =
    Math.abs(name.split('').reduce((acc: number, char: string) => acc + char.charCodeAt(0), 0)) %
    predefinedColors.length
  return predefinedColors[colorIndex]
})
</script>

<style scoped>
.staff-avatar-draggable {
  user-select: none;
  -webkit-user-select: none;
}

:global(.staff-sortable-chosen) .staff-avatar-draggable {
  border: 2px solid #3b82f6 !important;
  box-shadow: 0 4px 12px rgba(59, 130, 246, 0.3) !important;
  transform: scale(1.1) !important;
}

:global(.staff-sortable-drag) .staff-avatar-draggable {
  border: 3px solid #2563eb !important;
  box-shadow: 0 8px 20px rgba(37, 99, 235, 0.4) !important;
  transform: scale(1.15) rotate(3deg) !important;
  z-index: 1002 !important;
  position: relative !important;
}

@media (min-width: 768px) and (max-width: 1023px) {
  :global(.staff-sortable-chosen) .staff-avatar-draggable {
    transform: scale(1.15) !important;
    box-shadow: 0 6px 15px rgba(59, 130, 246, 0.35) !important;
  }

  :global(.staff-sortable-drag) .staff-avatar-draggable {
    transform: scale(1.2) rotate(2deg) !important;
    box-shadow: 0 10px 25px rgba(37, 99, 235, 0.45) !important;
    border-width: 3px !important;
  }
}

@media (max-width: 767px) {
  :global(.staff-sortable-chosen) .staff-avatar-draggable {
    transform: scale(1.08) !important;
  }

  :global(.staff-sortable-drag) .staff-avatar-draggable {
    transform: scale(1.12) rotate(1deg) !important;
  }
}
</style>
