// frontend/src/features/crm/PhoneCallTable.tsx
import { useState } from 'react'
import { useMutation, useQueryClient } from '@tanstack/react-query'
import { toast } from 'sonner'

import {
  apiErrorMessage,
  crmPhoneCallsListQueryKey,
  unlinkPhoneCallJobMutation,
  type PhoneCallRecordOut,
} from '@/api'
import { Button } from '@/components/ui/button'
import { ListTable } from '@/features/shared/ListTable'
import { formatDateTime } from '@/lib/format'

import { linkedJobOption, PhoneCallLinkJobDialog } from './PhoneCallLinkJobDialog'

/** `45s` under a minute, `1m 07s` above it — the seconds pad so a column of
    durations lines up. */
function formatDuration(seconds: number): string {
  const minutes = Math.floor(seconds / 60)
  const remainder = seconds % 60
  if (minutes === 0) return `${remainder}s`
  return `${minutes}m ${String(remainder).padStart(2, '0')}s`
}

function formatDirection(direction: string): string {
  if (direction === 'inbound') return 'Inbound'
  if (direction === 'outbound') return 'Outbound'
  if (direction === 'internal') return 'Internal'
  return 'Unknown'
}

/** The recording's playable URL, or null when there is nothing to play. */
function recordingUrl(call: PhoneCallRecordOut): string | null {
  if (call.recording === null) return null
  return call.recording.download_url
}

interface PhoneCallTableProps {
  isPending: boolean
  isError: boolean
  onRetry: () => void
  rows: readonly PhoneCallRecordOut[] | undefined
  emptyLabel: string
  /** False on surfaces that only report a call's job (the job's own History
      tab), where changing the link would move the call off the page. */
  allowJobLinking: boolean
  /** Offered only where the caller can host the assign panel; a call with no
      company is otherwise simply reported as unmatched. */
  onAssignNumber?: (call: PhoneCallRecordOut) => void
}

const HEAD_CLASS = 'px-3 py-2 text-left font-semibold text-gray-700'

/**
 * The one phone-call table: the calls page's triage queues and the job
 * History tab's linked calls draw the same seven columns, and linking is a
 * prop rather than a second component.
 */
export function PhoneCallTable({
  isPending,
  isError,
  onRetry,
  rows,
  emptyLabel,
  allowJobLinking,
  onAssignNumber,
}: PhoneCallTableProps) {
  const queryClient = useQueryClient()
  const [linkTarget, setLinkTarget] = useState<PhoneCallRecordOut | null>(null)

  const unlink = useMutation({
    ...unlinkPhoneCallJobMutation(),
    onSuccess: () => {
      // The refetch is authoritative rather than the response: unlinking moves
      // the call into the "needs job link" queue, which is a different row set.
      void queryClient.invalidateQueries({ queryKey: crmPhoneCallsListQueryKey() })
      toast.success('Phone call unlinked from job')
    },
    onError: (error) => toast.error(apiErrorMessage(error, 'Failed to unlink phone call')),
  })

  return (
    <>
      <ListTable
        isPending={isPending}
        isError={isError}
        onRetry={onRetry}
        loadingLabel="Loading calls..."
        errorLabel="Failed to load calls."
        rows={rows}
        emptyLabel={emptyLabel}
        automationId="PhoneCallTable"
        head={
          <tr className="border-b border-gray-200 bg-slate-50">
            <th scope="col" className={HEAD_CLASS}>
              Date &amp; Time
            </th>
            <th scope="col" className={HEAD_CLASS}>
              Number / Company
            </th>
            <th scope="col" className={HEAD_CLASS}>
              Our Number
            </th>
            <th scope="col" className={HEAD_CLASS}>
              Direction
            </th>
            <th scope="col" className={HEAD_CLASS}>
              Duration
            </th>
            <th scope="col" className={HEAD_CLASS}>
              Job
            </th>
            <th scope="col" className={HEAD_CLASS}>
              Recording
            </th>
          </tr>
        }
        renderRow={(call) => {
          const linkedJob = linkedJobOption(call)
          const url = recordingUrl(call)
          return (
            <tr
              key={call.id}
              data-automation-id={`PhoneCallTable-row-${call.id}`}
              className="border-b border-gray-100"
            >
              <td className="whitespace-nowrap px-3 py-2 text-gray-700">
                {formatDateTime(call.call_datetime)}
              </td>
              <td className="px-3 py-2">
                <div className="font-medium text-gray-900">
                  {call.company_name || call.external_number || '—'}
                </div>
                <div className="flex flex-wrap items-center gap-2 text-xs text-gray-500">
                  <span>{call.person_name || call.external_number || '—'}</span>
                  {onAssignNumber !== undefined &&
                    call.company === null &&
                    call.external_number !== null && (
                      <Button
                        type="button"
                        variant="ghost"
                        size="xs"
                        data-automation-id={`PhoneCallTable-assign-number-${call.id}`}
                        onClick={() => onAssignNumber(call)}
                      >
                        Assign number
                      </Button>
                    )}
                </div>
              </td>
              <td className="whitespace-nowrap px-3 py-2 text-gray-700">
                {call.our_number || '—'}
              </td>
              <td className="px-3 py-2">
                <span className="rounded-full border border-gray-300 px-2 py-0.5 text-xs text-gray-700">
                  {formatDirection(call.direction)}
                </span>
              </td>
              <td className="whitespace-nowrap px-3 py-2 text-gray-700">
                {formatDuration(call.duration_seconds)}
              </td>
              <td className="min-w-48 px-3 py-2">
                {linkedJob !== null ? (
                  <div className="flex flex-wrap items-center gap-2">
                    <span
                      data-automation-id={`PhoneCallTable-linked-job-${call.id}`}
                      className="rounded-full bg-gray-200 px-2 py-0.5 text-xs font-medium text-gray-700"
                    >
                      Job #{linkedJob.job_number}
                    </span>
                    {allowJobLinking && (
                      <>
                        <Button
                          type="button"
                          variant="ghost"
                          size="sm"
                          data-automation-id={`PhoneCallTable-change-job-${call.id}`}
                          onClick={() => setLinkTarget(call)}
                        >
                          Change
                        </Button>
                        <Button
                          type="button"
                          variant="ghost"
                          size="sm"
                          className="text-red-700 hover:text-red-800"
                          data-automation-id={`PhoneCallTable-unlink-job-${call.id}`}
                          disabled={unlink.isPending}
                          onClick={() => unlink.mutate({ path: { call_id: call.id } })}
                        >
                          Unlink
                        </Button>
                      </>
                    )}
                    <div className="basis-full text-xs text-gray-500">{linkedJob.name}</div>
                  </div>
                ) : call.company !== null && allowJobLinking ? (
                  <Button
                    type="button"
                    variant="outline"
                    size="sm"
                    data-automation-id={`PhoneCallTable-link-job-${call.id}`}
                    onClick={() => setLinkTarget(call)}
                  >
                    Link job
                  </Button>
                ) : (
                  <span className="text-xs text-gray-500">Assign company first</span>
                )}
              </td>
              <td className="min-w-64 px-3 py-2">
                {url === null ? (
                  <span className="text-xs text-gray-500">No recording</span>
                ) : (
                  // preload="none": one <audio> per row means "metadata" makes
                  // the browser fetch every recording on page load — about 2 MB
                  // of audio nobody played. The duration column already comes
                  // from duration_seconds, so there is nothing to preload for.
                  <audio
                    controls
                    preload="none"
                    src={url}
                    data-automation-id={`PhoneCallTable-recording-${call.id}`}
                    className="h-9 w-full max-w-sm"
                  />
                )}
              </td>
            </tr>
          )
        }}
      />
      <PhoneCallLinkJobDialog call={linkTarget} onClose={() => setLinkTarget(null)} />
    </>
  )
}

// frontend/src/components/crm/PhoneCallTable.vue
<template>
  <div class="overflow-x-auto rounded-md border border-gray-200 bg-white">
    <table class="min-w-full text-sm">
      <thead class="bg-slate-50 border-b">
        <tr>
          <th class="p-3 text-left font-semibold text-gray-700">Date & Time</th>
          <th class="p-3 text-left font-semibold text-gray-700">Number / Company</th>
          <th class="p-3 text-left font-semibold text-gray-700">Our Number</th>
          <th class="p-3 text-left font-semibold text-gray-700">Direction</th>
          <th class="p-3 text-left font-semibold text-gray-700">Duration</th>
          <th class="p-3 text-left font-semibold text-gray-700">Job</th>
          <th class="p-3 text-left font-semibold text-gray-700">Recording</th>
        </tr>
      </thead>
      <tbody>
        <tr v-if="calls.length === 0">
          <td colspan="7" class="p-6 text-center text-gray-500">{{ emptyText }}</td>
        </tr>
        <tr v-for="call in calls" :key="call.id" class="border-b last:border-b-0">
          <td class="p-3 whitespace-nowrap text-gray-700">
            {{ formatDateTime(call.call_datetime) }}
          </td>
          <td class="p-3">
            <div class="font-medium text-gray-900">
              {{ call.company_name || call.external_number || '-' }}
            </div>
            <div class="flex flex-wrap items-center gap-2 text-xs text-gray-500">
              <span>{{ call.person_name || call.external_number || '-' }}</span>
              <Button
                v-if="allowNumberAssignment && !call.company && call.external_number"
                variant="ghost"
                size="sm"
                class="h-6 px-2 text-xs"
                @click="$emit('assign-number', call)"
              >
                Assign number
              </Button>
            </div>
          </td>
          <td class="p-3 whitespace-nowrap text-gray-700">{{ call.our_number || '-' }}</td>
          <td class="p-3">
            <Badge variant="outline">{{ formatDirection(call.direction) }}</Badge>
          </td>
          <td class="p-3 whitespace-nowrap text-gray-700">
            {{ formatDuration(call.duration_seconds) }}
          </td>
          <td class="p-3 min-w-48">
            <div v-if="call.job" class="flex flex-wrap items-center gap-2">
              <Badge data-automation-id="PhoneCallTable-linked-job" variant="secondary">
                Job #{{ call.job_number }}
              </Badge>
              <Button
                v-if="allowJobLinking"
                :data-automation-id="`PhoneCallTable-change-job-${call.id}`"
                variant="ghost"
                size="sm"
                class="h-7 px-2"
                @click="openJobDialog(call)"
              >
                Change
              </Button>
              <Button
                v-if="allowJobLinking"
                :data-automation-id="`PhoneCallTable-unlink-job-${call.id}`"
                variant="ghost"
                size="sm"
                class="h-7 px-2 text-red-700 hover:text-red-800"
                :disabled="savingCallId === call.id"
                @click="unlinkJob(call)"
              >
                Unlink
              </Button>
              <div class="basis-full text-xs text-gray-500">{{ call.job_name }}</div>
            </div>
            <Button
              v-else-if="allowJobLinking && call.company"
              :data-automation-id="`PhoneCallTable-link-job-${call.id}`"
              variant="outline"
              size="sm"
              class="h-8"
              @click="openJobDialog(call)"
            >
              Link job
            </Button>
            <span v-else class="text-xs text-gray-500">Assign company first</span>
          </td>
          <td class="p-3 min-w-64">
            <!--
              preload="none": one <audio> per row means "metadata" makes the
              browser fetch every recording on page load. Duration is already
              shown in its own column from duration_seconds.
            -->
            <audio
              v-if="recordingDownloadUrl(call)"
              :src="recordingDownloadUrl(call) || undefined"
              controls
              preload="none"
              class="h-9 w-full max-w-sm"
            />
            <span v-else class="text-xs text-gray-500">No recording</span>
          </td>
        </tr>
      </tbody>
    </table>

    <Dialog :open="isDialogOpen" @update:open="handleDialogOpenChange">
      <DialogContent class="max-w-lg">
        <DialogHeader>
          <DialogTitle>Link Phone Call To Job</DialogTitle>
        </DialogHeader>
        <div class="space-y-4">
          <Input
            v-model="jobSearch"
            data-automation-id="PhoneCallTable-job-search"
            placeholder="Search job number or name"
          />
          <select
            v-model="selectedJobId"
            data-automation-id="PhoneCallTable-job-select"
            class="w-full rounded-md border border-gray-300 p-2 text-sm"
            :disabled="isLoadingJobs"
          >
            <option value="">Select job</option>
            <option v-for="job in filteredJobs" :key="job.job_id" :value="job.job_id">
              #{{ job.job_number }} - {{ job.name }}
            </option>
          </select>
          <div v-if="isLoadingJobs" class="text-sm text-gray-500">Loading jobs...</div>
          <div v-else-if="filteredJobs.length === 0" class="text-sm text-gray-500">
            No jobs found for this company
          </div>
        </div>
        <DialogFooter>
          <Button variant="outline" type="button" @click="closeJobDialog">Cancel</Button>
          <Button
            type="button"
            data-automation-id="PhoneCallTable-save-job-link"
            :disabled="!selectedCall || !selectedJobId || savingCallId === selectedCall.id"
            @click="saveJobLink"
          >
            Save
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  </div>
</template>

<script setup lang="ts">
import { computed, ref } from 'vue'
import { toast } from 'vue-sonner'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import {
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog'
import { Input } from '@/components/ui/input'
import { api } from '@/api/client'
import { schemas } from '@/api/generated/api'
import { formatDateTime } from '@/utils/string-formatting'
import type { z } from 'zod'

type PhoneCallRecord = z.infer<typeof schemas.PhoneCallRecord>
type CompanyJobHeader = z.infer<typeof schemas.CompanyJobHeader>

withDefaults(
  defineProps<{
    calls: PhoneCallRecord[]
    emptyText: string
    allowJobLinking?: boolean
    allowNumberAssignment?: boolean
  }>(),
  {
    allowJobLinking: true,
    allowNumberAssignment: false,
  },
)

const emit = defineEmits<{
  'call-updated': [call: PhoneCallRecord]
  'assign-number': [call: PhoneCallRecord]
}>()

const isDialogOpen = ref(false)
const selectedCall = ref<PhoneCallRecord | null>(null)
const selectedJobId = ref('')
const jobSearch = ref('')
const companyJobs = ref<CompanyJobHeader[]>([])
const isLoadingJobs = ref(false)
const savingCallId = ref<string | null>(null)

const filteredJobs = computed(() => {
  const search = jobSearch.value.trim().toLowerCase()
  if (!search) return companyJobs.value
  return companyJobs.value.filter((job) => {
    return (
      job.name.toLowerCase().includes(search) ||
      String(job.job_number).includes(search) ||
      job.status.toLowerCase().includes(search)
    )
  })
})

async function openJobDialog(call: PhoneCallRecord): Promise<void> {
  if (!call.company) {
    toast.error('Assign the call to a company before linking a job')
    return
  }
  selectedCall.value = call
  selectedJobId.value = call.job || ''
  jobSearch.value = ''
  isDialogOpen.value = true
  isLoadingJobs.value = true
  try {
    const response = await api.companies_jobs_retrieve({
      params: { company_id: call.company },
    })
    companyJobs.value = response.results
  } catch (error) {
    toast.error('Failed to load company jobs')
    console.error('Failed to load company jobs:', error)
    companyJobs.value = []
  } finally {
    isLoadingJobs.value = false
  }
}

function closeJobDialog(): void {
  isDialogOpen.value = false
  selectedCall.value = null
  selectedJobId.value = ''
  jobSearch.value = ''
  companyJobs.value = []
}

function handleDialogOpenChange(open: boolean): void {
  if (!open) {
    closeJobDialog()
  } else {
    isDialogOpen.value = true
  }
}

async function saveJobLink(): Promise<void> {
  if (!selectedCall.value || !selectedJobId.value) return
  const call = selectedCall.value
  savingCallId.value = call.id
  try {
    const updated = await api.linkPhoneCallJob(
      { job: selectedJobId.value },
      { params: { id: call.id } },
    )
    emit('call-updated', updated)
    toast.success('Phone call linked to job')
    closeJobDialog()
  } catch (error) {
    toast.error('Failed to link phone call')
    console.error('Failed to link phone call:', error)
  } finally {
    savingCallId.value = null
  }
}

async function unlinkJob(call: PhoneCallRecord): Promise<void> {
  savingCallId.value = call.id
  try {
    const updated = await api.unlinkPhoneCallJob(undefined, {
      params: { id: call.id },
    })
    emit('call-updated', updated)
    toast.success('Phone call unlinked from job')
  } catch (error) {
    toast.error('Failed to unlink phone call')
    console.error('Failed to unlink phone call:', error)
  } finally {
    savingCallId.value = null
  }
}

function formatDirection(value: string): string {
  if (value === 'inbound') return 'Inbound'
  if (value === 'outbound') return 'Outbound'
  if (value === 'internal') return 'Internal'
  return 'Unknown'
}

function formatDuration(seconds: number): string {
  const minutes = Math.floor(seconds / 60)
  const remainder = seconds % 60
  if (minutes === 0) return `${remainder}s`
  return `${minutes}m ${remainder.toString().padStart(2, '0')}s`
}

function recordingDownloadUrl(call: PhoneCallRecord): string | null {
  const downloadUrl = call.recording?.download_url
  return typeof downloadUrl === 'string' ? downloadUrl : null
}
</script>
