// frontend/src/components/CompanyLookup.vue
<template>
  <div class="relative">
    <label :for="id" class="block text-sm font-medium text-gray-700 mb-1">
      {{ label }}
      <span v-if="required" class="text-red-500">*</span>
    </label>

    <div class="flex space-x-2">
      <div class="flex-1 relative">
        <input
          :id="id"
          ref="inputEl"
          v-model="searchQuery"
          type="text"
          :placeholder="placeholder"
          :required="required"
          data-automation-id="CompanyLookup-input"
          class="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:border-transparent"
          @input="handleInput"
          @focus="handleFocus"
          @blur="handleBlur"
          @keydown="handleKeydown"
          autocomplete="off"
        />

        <div
          v-if="isLoading || isCreatingQuickCompany"
          class="absolute right-3 top-1/2 transform -translate-y-1/2"
        >
          <div class="animate-spin rounded-full h-4 w-4 border-b-2 border-blue-600"></div>
        </div>

        <div
          v-if="showSuggestions && (suggestions.length > 0 || searchQuery.length >= 3)"
          data-automation-id="CompanyLookup-results"
          class="absolute z-50 w-full mt-1 bg-white border border-gray-300 rounded-md shadow-lg max-h-60 overflow-y-auto"
        >
          <div
            v-for="(company, index) in suggestions"
            :key="company.id"
            role="option"
            :data-automation-id="`CompanyLookup-option-${company.id}`"
            class="px-4 py-2 hover:bg-blue-50 cursor-pointer border-b border-gray-100 last:border-b-0"
            @mousedown.prevent="selectCompany(company, index + 1)"
          >
            <div class="font-medium text-gray-900">{{ company.name }}</div>
          </div>

          <div
            v-if="searchQuery.length >= 3"
            class="px-4 py-2 hover:bg-green-50 cursor-pointer border-t border-gray-200 text-green-700 font-medium"
            data-automation-id="CompanyLookup-create-new"
            @mousedown.prevent="handleCreateNew"
          >
            <div class="flex items-center justify-between">
              <div class="flex items-center">
                <Plus class="w-4 h-4 mr-2" />
                Add new {{ supplierLookup.value ? 'supplier' : 'company' }} "{{ searchQuery }}"
              </div>
              <div class="text-xs text-gray-500">or press Ctrl+Enter</div>
            </div>
          </div>

          <div
            v-if="suggestions.length === 0 && searchQuery.length >= 3 && !isLoading"
            class="px-4 py-2 text-gray-500 text-center"
          >
            No companies found
          </div>
        </div>
      </div>

      <div class="flex items-end">
        <div
          :class="[
            'px-3 py-2 rounded-md text-xs font-medium flex items-center space-x-1',
            xeroValid
              ? 'bg-green-100 text-green-800 border border-green-200'
              : 'bg-red-100 text-red-800 border border-red-200',
          ]"
          :title="hasValidXeroId ? 'Company has Xero ID' : 'Company missing Xero ID'"
          :data-automation-id="
            xeroValid ? 'CompanyLookup-xero-valid' : 'CompanyLookup-xero-invalid'
          "
          v-if="!searchMode"
        >
          <component :is="xeroValid ? CheckCircle : XCircle" class="w-3 h-3" />
          <span>Xero</span>
        </div>
      </div>
    </div>

    <div v-if="selectedCompany && !editMode" class="mt-2 p-2 bg-blue-50 rounded border">
      <div class="text-sm font-medium text-blue-900">{{ selectedCompany.name }}</div>
      <div v-if="selectedCompany.email" class="text-xs text-blue-700">
        {{ selectedCompany.email }}
      </div>
    </div>

    <CreateCompanyModal
      :is-open="showCreateModal"
      :initial-name="searchQuery"
      @update:is-open="showCreateModal = $event"
      @company-created="handleCompanyCreated"
    />
  </div>
</template>

<script setup lang="ts">
import { ref, watch, onMounted, computed } from 'vue'
import { Plus, CheckCircle, XCircle } from 'lucide-vue-next'
import { logCompanySearchClick, useCompanyLookup } from '@/composables/useCompanyLookup'
import CreateCompanyModal from '@/components/CreateCompanyModal.vue'
import type { Company } from '@/composables/useCompanyLookup'
import { api } from '@/api/client'
import { toast } from 'vue-sonner'
import { debugLog } from '../utils/debug'

const props = withDefaults(
  defineProps<{
    id: string
    label: string
    placeholder?: string
    required?: boolean
    modelValue?: string
    supplierLookup?: { value: boolean }
    searchMode?: boolean
    editMode?: boolean
  }>(),
  {
    placeholder: 'Search for a company...',
    required: false,
    modelValue: '',
    supplierLookup: () => ({ value: false }),
    searchMode: false,
  },
)

const emit = defineEmits<{
  'update:modelValue': [value: string]
  'update:selectedCompany': [company: Company | null]
  'update:selectedId': [id: string]
}>()

const {
  searchQuery,
  suggestions,
  isLoading,
  showSuggestions,
  selectedCompany,
  hasValidXeroId,
  handleInputChange,
  selectCompany: selectCompanyFromComposable,
  hideSuggestions,
  preserveSelectedCompany,
} = useCompanyLookup({ supplierLookup: props.supplierLookup })

// Simple check: does the selected company have a Xero ID?
const xeroValid = computed(() => hasValidXeroId.value)

const showCreateModal = ref(false)
const inputEl = ref<HTMLInputElement | null>(null) // Template ref for the input element
const isCreatingQuickCompany = ref(false)

const blurTimeout = ref<ReturnType<typeof setTimeout> | null>(null)

if (props.modelValue) {
  searchQuery.value = props.modelValue
}

const suppressFocusUntil = ref(0)

function closeLookup() {
  if (blurTimeout.value) {
    clearTimeout(blurTimeout.value)
    blurTimeout.value = null
  }

  suppressFocusUntil.value = Date.now() + 500

  showSuggestions.value = false
  showCreateModal.value = false

  inputEl.value?.blur()
}

const handleInput = (event: Event) => {
  const target = event.target as HTMLInputElement
  const value = target.value

  handleInputChange(value)
  emit('update:modelValue', value)
}

const handleFocus = () => {
  if (blurTimeout.value) clearTimeout(blurTimeout.value)

  if (Date.now() < suppressFocusUntil.value) return

  if (searchQuery.value.length >= 3) {
    showSuggestions.value = true
  }
}

const handleBlur = () => {
  blurTimeout.value = setTimeout(() => {
    hideSuggestions()
  }, 200)
}

const selectCompany = (company: Company, rank: number | null = null) => {
  const query = searchQuery.value
  preserveSelectedCompany()
  selectCompanyFromComposable(company)
  logCompanySearchClick(company, query, rank, 'company_lookup')
  emit('update:modelValue', company.name)
  emit('update:selectedCompany', company)
  emit('update:selectedId', company.id)
  showSuggestions.value = false
}

const handleCreateNew = () => {
  showCreateModal.value = true
  hideSuggestions()
}

const handleKeydown = async (event: KeyboardEvent) => {
  if (event.ctrlKey && event.key === 'Enter') {
    event.preventDefault()

    const companyName = searchQuery.value.trim()
    if (companyName.length >= 3) {
      await createQuickCompany(companyName)
    }
  }
}

const createQuickCompany = async (companyName: string) => {
  if (isCreatingQuickCompany.value) return

  isCreatingQuickCompany.value = true

  try {
    const companyData = {
      name: companyName,
      email: null,
      address: '',
      is_account_customer: false,
    }

    const result = await api.companies_create_create(companyData)

    if (result.success && result.company) {
      if (!result.company.xero_contact_id) {
        throw new Error('Company was created but does not have a Xero ID')
      }

      const newCompany: Company = {
        ...result.company,
        email: result.company.email ?? '',
        address: result.company.address ?? '',
        xero_contact_id: result.company.xero_contact_id ?? '',
      }

      selectCompany(newCompany)
      searchQuery.value = newCompany.name
      emit('update:modelValue', newCompany.name)

      toast.success(`Company "${companyName}" created successfully!`, {
        position: 'bottom-left',
      })
    } else {
      throw new Error(result.message || 'Failed to create company')
    }
  } catch (error) {
    toast.error(`Failed to create company: ${error instanceof Error ? error.message : error}`, {
      position: 'bottom-left',
    })
    console.error('Quick company creation error:', error)
  } finally {
    isCreatingQuickCompany.value = false
  }
}

const handleCompanyCreated = (company: Company) => {
  selectCompany(company)

  searchQuery.value = company.name
  emit('update:modelValue', company.name)

  closeLookup()
}

watch(
  () => props.modelValue,
  (newValue) => {
    if (newValue !== searchQuery.value) {
      searchQuery.value = newValue
      // Preserve selected company when dialog reopens
      preserveSelectedCompany()
    }
  },
  { immediate: true },
)

watch(selectedCompany, (newCompany, oldCompany) => {
  // Only emit if this is a real change, not during initial loading
  if (newCompany?.id !== oldCompany?.id) {
    if (newCompany) {
      emit('update:selectedCompany', newCompany)
      emit('update:selectedId', newCompany.id)
    } else {
      emit('update:selectedCompany', null)
      emit('update:selectedId', '')
    }
  }
})

// Preserve company selection when component mounts
onMounted(() => {
  debugLog('Props value: ', props)
  preserveSelectedCompany(props.modelValue || '')
})
</script>

// frontend/src/features/company/CompanyLookup.tsx
import { useEffect, useMemo, useRef, useState } from 'react'
import { useMutation, useQuery } from '@tanstack/react-query'
import { CheckCircle, Plus, XCircle } from 'lucide-react'
import { toast } from 'sonner'

import {
  apiErrorMessage,
  companiesCreateCreateMutation,
  companiesSearchRetrieveOptions,
  type CompanySearchResult,
} from '@/api'
import { CreateCompanyModal } from './CreateCompanyModal'
import { requireXeroLinkedCompany } from './create-company'
import { hasXeroContact } from './xero-contact'

const MIN_QUERY_LENGTH = 3

interface CompanyLookupProps {
  id: string
  label: string
  required?: boolean
  placeholder?: string
  selectedCompany: CompanySearchResult | null
  onSelectCompany: (company: CompanySearchResult | null) => void
}

/**
 * Typeahead company search. Selection is owned by the parent: the input shows
 * the selected company's name until the user types again, at which point the
 * selection is cleared (a stale id behind an edited name would submit the
 * wrong company).
 */
export function CompanyLookup({
  id,
  label,
  required = false,
  placeholder = 'Search for a company...',
  selectedCompany,
  onSelectCompany,
}: CompanyLookupProps) {
  const [query, setQuery] = useState('')
  const [showSuggestions, setShowSuggestions] = useState(false)
  const [showCreateModal, setShowCreateModal] = useState(false)
  const [activeCompanyId, setActiveCompanyId] = useState<string | null>(null)
  const blurTimeout = useRef<ReturnType<typeof setTimeout> | null>(null)
  const createCompany = useMutation(companiesCreateCreateMutation())

  const inputValue = selectedCompany ? selectedCompany.name : query
  const searchEnabled = !selectedCompany && query.length >= MIN_QUERY_LENGTH

  const search = useQuery({
    ...companiesSearchRetrieveOptions({ query: { q: query } }),
    enabled: searchEnabled,
  })
  const suggestions = useMemo(() => search.data?.results ?? [], [search.data])
  const listboxId = `${id}-results`

  useEffect(() => {
    if (!showSuggestions || suggestions.length === 0) {
      setActiveCompanyId(null)
      return
    }
    setActiveCompanyId((current) =>
      suggestions.some((company) => company.id === current) ? current : suggestions[0]!.id,
    )
  }, [showSuggestions, suggestions])

  const handleInput = (value: string) => {
    if (selectedCompany) {
      onSelectCompany(null)
    }
    setQuery(value)
    setShowSuggestions(value.length >= MIN_QUERY_LENGTH)
  }

  const handleSelect = (company: CompanySearchResult) => {
    onSelectCompany(company)
    setQuery('')
    setShowSuggestions(false)
  }

  const handleCompanyCreated = (company: CompanySearchResult) => {
    setShowCreateModal(false)
    handleSelect(company)
    toast.success(`Company "${company.name}" created successfully!`)
  }

  const quickCreateCompany = async (companyName: string) => {
    // The same payload the modal sends; v1 defaulted new companies to cash
    // customers (is_account_customer false) on both paths.
    try {
      const response = await createCompany.mutateAsync({
        body: { name: companyName, is_account_customer: false },
      })
      handleCompanyCreated(requireXeroLinkedCompany(response))
    } catch (error) {
      toast.error(apiErrorMessage(error, 'Failed to create company.'))
    }
  }

  const handleKeyDown = (event: React.KeyboardEvent<HTMLInputElement>) => {
    if (event.ctrlKey && event.key === 'Enter') {
      event.preventDefault()
      const companyName = query.trim()
      if (companyName.length >= MIN_QUERY_LENGTH && !createCompany.isPending) {
        void quickCreateCompany(companyName)
      }
      return
    }
    if (event.key === 'Escape') {
      setShowSuggestions(false)
      setActiveCompanyId(null)
      return
    }
    if (!searchEnabled || suggestions.length === 0) {
      return
    }
    if (event.key === 'Enter' && showSuggestions && activeCompanyId !== null) {
      event.preventDefault()
      const company = suggestions.find((candidate) => candidate.id === activeCompanyId)
      if (company) {
        handleSelect(company)
      }
      return
    }
    if (event.key !== 'ArrowDown' && event.key !== 'ArrowUp') {
      return
    }

    event.preventDefault()
    setShowSuggestions(true)
    const currentIndex = suggestions.findIndex((company) => company.id === activeCompanyId)
    const offset = event.key === 'ArrowDown' ? 1 : -1
    const nextIndex =
      currentIndex === -1 ? 0 : (currentIndex + offset + suggestions.length) % suggestions.length
    setActiveCompanyId(suggestions[nextIndex]!.id)
  }

  const xeroValid = hasXeroContact(selectedCompany)

  return (
    <div className="relative">
      <label htmlFor={id} className="mb-1 block text-sm font-medium text-gray-700">
        {label} {required && <span className="text-red-500">*</span>}
      </label>

      <div className="flex space-x-2">
        <div className="relative flex-1">
          <input
            id={id}
            type="text"
            value={inputValue}
            placeholder={placeholder}
            required={required}
            data-automation-id="CompanyLookup-input"
            autoComplete="off"
            role="combobox"
            aria-autocomplete="list"
            aria-expanded={showSuggestions}
            aria-controls={listboxId}
            aria-activedescendant={
              showSuggestions && activeCompanyId !== null
                ? `${listboxId}-option-${activeCompanyId}`
                : undefined
            }
            className="w-full rounded-md border border-gray-300 px-3 py-2 focus:border-transparent focus:ring-2 focus:ring-blue-500"
            onChange={(event) => handleInput(event.target.value)}
            onKeyDown={handleKeyDown}
            onFocus={() => {
              // Refocusing within the blur grace period must not let the
              // stale timer close a dropdown the user is back inside.
              if (blurTimeout.current !== null) {
                clearTimeout(blurTimeout.current)
                blurTimeout.current = null
              }
              if (!selectedCompany && query.length >= MIN_QUERY_LENGTH) {
                setShowSuggestions(true)
              }
            }}
            // The 200ms grace period lets an option's mousedown land before
            // the dropdown unmounts; closing on blur alone loses the click.
            onBlur={() => {
              blurTimeout.current = setTimeout(() => setShowSuggestions(false), 200)
            }}
          />

          {showSuggestions && (suggestions.length > 0 || query.length >= MIN_QUERY_LENGTH) && (
            <div
              id={listboxId}
              role="listbox"
              aria-label={`${label} search results`}
              data-automation-id="CompanyLookup-results"
              className="absolute z-50 mt-1 max-h-60 w-full overflow-y-auto rounded-md border border-gray-300 bg-white shadow-lg"
            >
              {suggestions.map((company) => (
                <div
                  key={company.id}
                  id={`${listboxId}-option-${company.id}`}
                  role="option"
                  aria-selected={activeCompanyId === company.id}
                  data-automation-id={`CompanyLookup-option-${company.id}`}
                  className={`cursor-pointer border-b border-gray-100 px-4 py-2 last:border-b-0 hover:bg-blue-50 ${
                    activeCompanyId === company.id ? 'bg-blue-50' : ''
                  }`}
                  onMouseEnter={() => setActiveCompanyId(company.id)}
                  onMouseDown={(event) => {
                    event.preventDefault()
                    handleSelect(company)
                  }}
                >
                  <div className="font-medium text-gray-900">{company.name}</div>
                </div>
              ))}

              {query.length >= MIN_QUERY_LENGTH && (
                <div
                  role="option"
                  aria-selected={false}
                  id={`${listboxId}-create-new`}
                  className="cursor-pointer border-t border-gray-200 px-4 py-2 font-medium text-green-700 hover:bg-green-50"
                  data-automation-id="CompanyLookup-create-new"
                  onMouseDown={(event) => {
                    event.preventDefault()
                    setShowSuggestions(false)
                    setShowCreateModal(true)
                  }}
                >
                  <div className="flex items-center justify-between">
                    <div className="flex items-center">
                      <Plus className="mr-2 h-4 w-4" />
                      Add new company &quot;{query}&quot;
                    </div>
                    <div className="text-xs text-gray-500">or press Ctrl+Enter</div>
                  </div>
                </div>
              )}

              {suggestions.length === 0 &&
                query.length >= MIN_QUERY_LENGTH &&
                !search.isPending && (
                  <div className="px-4 py-2 text-center text-gray-500">No companies found</div>
                )}
            </div>
          )}
        </div>

        <div className="flex items-end">
          <div
            className={
              xeroValid
                ? 'flex items-center space-x-1 rounded-md border border-green-200 bg-green-100 px-3 py-2 text-xs font-medium text-green-800'
                : 'flex items-center space-x-1 rounded-md border border-red-200 bg-red-100 px-3 py-2 text-xs font-medium text-red-800'
            }
            title={xeroValid ? 'Company has Xero ID' : 'Company missing Xero ID'}
            data-automation-id={
              xeroValid ? 'CompanyLookup-xero-valid' : 'CompanyLookup-xero-invalid'
            }
          >
            {xeroValid ? <CheckCircle className="h-3 w-3" /> : <XCircle className="h-3 w-3" />}
            <span>Xero</span>
          </div>
        </div>
      </div>

      {selectedCompany && (
        <div className="mt-2 rounded border bg-blue-50 p-2">
          <div className="text-sm font-medium text-blue-900">{selectedCompany.name}</div>
          {selectedCompany.email && (
            <div className="text-xs text-blue-700">{selectedCompany.email}</div>
          )}
        </div>
      )}

      <CreateCompanyModal
        open={showCreateModal}
        initialName={query}
        onClose={() => setShowCreateModal(false)}
        onCreated={handleCompanyCreated}
      />
    </div>
  )
}
