// frontend/src/features/timesheet/TimesheetJobPicker.tsx
import { useEffect, useMemo, useRef, useState } from 'react'

import type { TimesheetJobOut } from '@/api'
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover'
import { rateForSubtype } from './labourRates'

const TYPED_SEARCH_LIMIT = 15

export interface TimesheetJobPickerProps {
  /** `SmartTimesheetTable-jobPicker-${rowIndex}` — every inner id derives from it. */
  automationIdPrefix: string
  jobs: readonly TimesheetJobOut[]
  selected: TimesheetJobOut | null
  disabled: boolean
  /** Rendered as data-entry-seq on the trigger (the keyboard spec binds rows by it). */
  entrySeq: number | null
  gridRow: number
  onSelect: (job: TimesheetJobOut) => void
}

function statusLabel(status: string | null | undefined): string {
  switch (status) {
    case 'draft':
      return 'Draft'
    case 'awaiting_approval':
      return 'Awaiting Approval'
    case 'approved':
      return 'Approved'
    case 'in_progress':
      return 'In Progress'
    case 'recently_completed':
      return 'Recently Completed'
    case 'archived':
      return 'Archived'
    case 'special':
      return 'Special'
    case 'on_hold':
      return 'On Hold'
    case 'unusual':
      return 'Unusual'
    default:
      return ''
  }
}

/** Workshop charge-out rate shown in the picker (rates are per labour subtype). */
function jobDisplayRate(job: TimesheetJobOut): number {
  return rateForSubtype(job.labour_rates, null)
}

/**
 * The timesheet job picker (v1 TimesheetJobPicker port). Not cmdk: the
 * keyboard contract is v1's — a maintained highlight index, Enter picking
 * the highlighted (or sole) match, and Tab picking the highlighted match so
 * the caller can move focus on — which fights cmdk's internal selection
 * model rather than reusing it.
 */
export function TimesheetJobPicker({
  automationIdPrefix,
  jobs,
  selected,
  disabled,
  entrySeq,
  gridRow,
  onSelect,
}: TimesheetJobPickerProps) {
  const [open, setOpen] = useState(false)
  const [search, setSearch] = useState('')
  const [highlighted, setHighlighted] = useState(-1)
  const searchRef = useRef<HTMLInputElement>(null)

  const filtered = useMemo<TimesheetJobOut[]>(() => {
    const term = search.trim().toLowerCase()
    if (!term) {
      // Blank search shows the whole (workload-bounded) list, selected first.
      if (selected) {
        return [selected, ...jobs.filter((job) => job.id !== selected.id)]
      }
      return [...jobs]
    }
    return jobs
      .filter((job) => {
        const num = String(job.job_number).toLowerCase()
        const name = job.name.toLowerCase()
        const company = (job.company_name ?? '').toLowerCase()
        return num.includes(term) || name.includes(term) || company.includes(term)
      })
      .slice(0, TYPED_SEARCH_LIMIT)
  }, [jobs, search, selected])

  // The default highlight is the first match, reset when the TERM changes —
  // not when the filtered array's identity changes, because a parent
  // re-render rebuilds the jobs array and would clobber arrow-key state.
  const filteredCount = filtered.length
  useEffect(() => {
    if (!open) return
    setHighlighted(filteredCount > 0 ? 0 : -1)
  }, [open, search, filteredCount])

  useEffect(() => {
    if (!open) {
      setSearch('')
      setHighlighted(-1)
    }
  }, [open])

  const pick = (job: TimesheetJobOut) => {
    onSelect(job)
    setOpen(false)
  }

  const onSearchKeyDown = (event: React.KeyboardEvent<HTMLInputElement>) => {
    if (filtered.length === 0) return
    switch (event.key) {
      case 'ArrowDown':
        event.preventDefault()
        setHighlighted((current) => Math.min(current + 1, filtered.length - 1))
        break
      case 'ArrowUp':
        event.preventDefault()
        setHighlighted((current) => Math.max(current - 1, 0))
        break
      case 'Enter':
        event.preventDefault()
        if (highlighted >= 0) {
          pick(filtered[highlighted]!)
        } else if (filtered.length === 1) {
          pick(filtered[0]!)
        }
        break
      case 'Tab':
        // Tab commits the highlighted job and lets the caller's focus logic
        // take over (the grid moves focus to the hours cell after a pick).
        if (highlighted >= 0) {
          event.preventDefault()
          pick(filtered[highlighted]!)
        }
        break
      case 'Escape':
        event.preventDefault()
        setOpen(false)
        break
      default:
        break
    }
  }

  const triggerLabel = selected ? `#${selected.job_number}` : 'Select job…'

  return (
    <Popover open={open} onOpenChange={setOpen}>
      <PopoverTrigger asChild>
        <button
          type="button"
          disabled={disabled}
          title={triggerLabel}
          className={`block w-full max-w-[10ch] truncate rounded border border-transparent px-2 py-1 text-left text-sm hover:border-slate-300 disabled:cursor-not-allowed disabled:opacity-50 ${selected ? '' : 'text-slate-400'}`}
          data-automation-id={`${automationIdPrefix}-trigger`}
          data-entry-seq={entrySeq ?? undefined}
          data-grid-nav-cell="true"
          data-grid-row={gridRow}
          data-grid-col="jobNumber"
          onFocus={() => {
            // An empty enabled row opens straight into search — the create
            // flow's focus handoff lands here and must not need a click.
            if (!disabled && !selected) setOpen(true)
          }}
        >
          {triggerLabel}
          {selected?.is_urgent && (
            <span className="ml-1 inline-block rounded bg-red-50 px-1 text-[10px] font-bold text-red-600">
              !
            </span>
          )}
        </button>
      </PopoverTrigger>
      <PopoverContent
        className="w-[360px] p-0"
        align="start"
        onOpenAutoFocus={(event) => {
          // Take over the focus trap so the search input gets focus.
          event.preventDefault()
          searchRef.current?.focus()
        }}
      >
        <div className="border-b border-slate-200 p-2">
          <input
            ref={searchRef}
            value={search}
            placeholder="Search jobs… (job number, name, or company)"
            className="h-8 w-full rounded border border-slate-200 px-2 text-sm"
            data-automation-id={`${automationIdPrefix}-search`}
            onChange={(event) => setSearch(event.target.value)}
            onKeyDown={onSearchKeyDown}
          />
        </div>
        <div
          className="max-h-[300px] overflow-y-auto"
          data-automation-id={`${automationIdPrefix}-list`}
        >
          {filtered.length === 0 && (
            <div className="px-3 py-2 text-sm italic text-slate-500">No jobs found</div>
          )}
          {filtered.map((job, index) => (
            <div
              key={job.id}
              className={`cursor-pointer border-b border-slate-100 px-3 py-2 text-sm last:border-b-0 ${index === highlighted ? 'bg-blue-50' : 'hover:bg-slate-50'}`}
              data-automation-id={`${automationIdPrefix}-option-${job.job_number}`}
              onMouseEnter={() => setHighlighted(index)}
              onClick={() => pick(job)}
            >
              <div className="flex items-start justify-between gap-2">
                <span className="shrink-0 font-semibold text-slate-800">#{job.job_number}</span>
                <div className="flex items-center gap-1">
                  {job.is_urgent && (
                    <span className="rounded bg-red-50 px-1.5 py-0.5 text-[10px] font-bold text-red-600">
                      URGENT
                    </span>
                  )}
                  {statusLabel(job.status) && (
                    <span className="text-right text-[11px] font-medium leading-tight text-slate-500">
                      {statusLabel(job.status)}
                    </span>
                  )}
                </div>
              </div>
              <div className="mt-0.5 break-words font-medium leading-tight text-slate-700">
                {job.name}
              </div>
              <div className="text-xs leading-tight text-slate-500">
                Company: {job.company_name ?? 'No Company'}
              </div>
              <div className="text-[11px] leading-tight text-slate-400">
                Rate: ${jobDisplayRate(job)}/hr
              </div>
            </div>
          ))}
        </div>
      </PopoverContent>
    </Popover>
  )
}

// frontend/src/components/timesheet/TimesheetJobPicker.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { Popover, PopoverContent, PopoverTrigger } from '../ui/popover'
import { Input } from '../ui/input'
import { gridCellAttrs } from '../../composables/useGridKeyboardNav'

import { schemas } from '../../api/generated/api'
import type { z } from 'zod'
import { rateForSubtype } from '../../utils/labourRates'

type Job = z.infer<typeof schemas.ModernTimesheetJob>

/** Workshop charge-out rate shown in the picker (rates are per labour subtype). */
function jobDisplayRate(job: Job): number {
  return rateForSubtype(job.labour_rates, null)
}

const props = withDefaults(
  defineProps<{
    modelValue: number | null
    jobs: Job[]
    disabled?: boolean
    placeholder?: string
    automationIdPrefix?: string
    gridRowIndex?: number
    gridCol?: string
    entrySeq?: number | null
  }>(),
  {
    disabled: false,
    placeholder: 'Select job…',
    automationIdPrefix: 'TimesheetJobPicker',
  },
)

const emit = defineEmits<{
  select: [job: Job]
  gridKeydown: [event: KeyboardEvent]
}>()

const open = ref(false)
const search = ref('')
const highlightedIndex = ref(-1)
// shadcn `Input` does not `defineExpose` the underlying element, so a template
// ref on it lands on the component instance. We reach the DOM input via `$el`.
const searchInput = ref<{ $el?: HTMLInputElement } | null>(null)

const selectedJob = computed<Job | null>(() => {
  if (props.modelValue == null) return null
  return props.jobs.find((j) => j.job_number === props.modelValue) ?? null
})

const triggerLabel = computed(() => {
  const j = selectedJob.value
  if (!j) return props.placeholder
  // Just the job number; the full name lives in the dedicated Job Name column.
  return `#${j.job_number}`
})

// `props.jobs` is the active-jobs-for-timesheet set served by
// `timesheets_jobs_retrieve()` — bounded by live shop workload (tens to
// low-hundreds), not the full job table. Blank search shows the full list so
// a user can pick by eye; typed search trims to top 15 matches.
const filtered = computed<Job[]>(() => {
  const term = search.value.trim().toLowerCase()
  if (!term) {
    if (selectedJob.value) {
      const others = props.jobs.filter((j) => j.id !== selectedJob.value!.id)
      return [selectedJob.value, ...others]
    }
    return [...props.jobs]
  }
  return props.jobs
    .filter((j) => {
      const num = String(j.job_number ?? '').toLowerCase()
      const name = (j.name ?? '').toLowerCase()
      const company = (j.company_name ?? '').toLowerCase()
      return num.includes(term) || name.includes(term) || company.includes(term)
    })
    .slice(0, 15)
})

watch(
  () => filtered.value,
  () => {
    highlightedIndex.value = filtered.value.length > 0 ? 0 : -1
  },
)

watch(open, (isOpen) => {
  if (!isOpen) {
    search.value = ''
    highlightedIndex.value = -1
  } else {
    // Focus-on-open is driven by PopoverContent's @open-auto-focus, which fires
    // after the content mounts — a nextTick guess here silently no-ops under load.
  }
})

function onOpenAutoFocus(e: Event): void {
  // Take over reka-ui's default focus trap so the search input gets focus.
  e.preventDefault()
  // The element is guaranteed present: this event fires after PopoverContent mounts.
  searchInput.value?.$el?.focus()
}

function statusColor(status: string | null | undefined): string {
  switch (status) {
    case 'approved':
    case 'accepted_quote':
    case 'awaiting_materials':
    case 'awaiting_staff':
    case 'awaiting_site_availability':
    case 'in_progress':
      return '#059669'
    case 'completed':
    case 'recently_completed':
    case 'archived':
      return '#6B7280'
    case 'special':
      return '#DC2626'
    case 'draft':
    case 'quoting':
      return '#D97706'
    case 'awaiting_approval':
      return '#3B82F6'
    case 'on_hold':
    case 'unusual':
      return '#EAB308'
    case 'rejected':
      return '#EF4444'
    default:
      return '#D97706'
  }
}

function statusLabel(status: string | null | undefined): string {
  switch (status) {
    case 'draft':
      return 'Draft'
    case 'awaiting_approval':
      return 'Awaiting Approval'
    case 'approved':
      return 'Approved'
    case 'in_progress':
      return 'In Progress'
    case 'recently_completed':
      return 'Recently Completed'
    case 'archived':
      return 'Archived'
    case 'special':
      return 'Special'
    case 'on_hold':
      return 'On Hold'
    case 'unusual':
      return 'Unusual'
    default:
      return ''
  }
}

function pickJob(job: Job) {
  emit('select', job)
  open.value = false
}

function openEmptyPicker(): void {
  if (props.disabled || selectedJob.value) return
  open.value = true
}

function onKeyDown(e: KeyboardEvent) {
  if (filtered.value.length === 0) return
  switch (e.key) {
    case 'ArrowDown':
      e.preventDefault()
      highlightedIndex.value = Math.min(highlightedIndex.value + 1, filtered.value.length - 1)
      break
    case 'ArrowUp':
      e.preventDefault()
      highlightedIndex.value = Math.max(highlightedIndex.value - 1, 0)
      break
    case 'Enter':
      e.preventDefault()
      if (highlightedIndex.value >= 0) {
        pickJob(filtered.value[highlightedIndex.value])
      } else if (filtered.value.length === 1) {
        pickJob(filtered.value[0])
      }
      break
    case 'Tab':
      if (highlightedIndex.value >= 0) {
        e.preventDefault()
        pickJob(filtered.value[highlightedIndex.value])
      }
      break
    case 'Escape':
      e.preventDefault()
      open.value = false
      break
  }
}
</script>

<template>
  <Popover v-model:open="open">
    <PopoverTrigger as-child>
      <button
        type="button"
        :disabled="disabled"
        class="job-picker-trigger block w-full max-w-[10ch] text-left truncate text-sm px-2 py-1 rounded border border-transparent hover:border-slate-300 disabled:opacity-50 disabled:cursor-not-allowed"
        :class="{ 'text-slate-400': !selectedJob }"
        :data-automation-id="`${automationIdPrefix}-trigger`"
        :title="triggerLabel"
        :data-entry-seq="props.entrySeq"
        v-bind="
          props.gridRowIndex != null
            ? gridCellAttrs(props.gridRowIndex, props.gridCol ?? 'jobNumber')
            : {}
        "
        @focus="openEmptyPicker"
        @keydown="(e) => emit('gridKeydown', e)"
      >
        {{ triggerLabel }}
        <span
          v-if="selectedJob?.is_urgent"
          class="inline-block ml-1 text-[10px] font-bold text-red-600 bg-red-50 px-1 rounded"
        >
          !
        </span>
      </button>
    </PopoverTrigger>
    <PopoverContent class="p-0 w-[360px]" align="start" @open-auto-focus="onOpenAutoFocus">
      <div class="p-2 border-b border-slate-200">
        <Input
          ref="searchInput"
          v-model="search"
          placeholder="Search jobs… (job number, name, or company)"
          class="h-8 text-sm"
          :data-automation-id="`${automationIdPrefix}-search`"
          @keydown="onKeyDown"
        />
      </div>
      <div class="max-h-[300px] overflow-y-auto" :data-automation-id="`${automationIdPrefix}-list`">
        <div v-if="filtered.length === 0" class="px-3 py-2 text-sm text-slate-500 italic">
          No jobs found
        </div>
        <div
          v-for="(job, idx) in filtered"
          :key="job.id"
          class="px-3 py-2 cursor-pointer border-b border-slate-100 last:border-b-0 text-sm"
          :class="idx === highlightedIndex ? 'bg-blue-50' : 'hover:bg-slate-50'"
          :data-automation-id="`${automationIdPrefix}-option-${job.job_number}`"
          @mouseenter="highlightedIndex = idx"
          @click="pickJob(job)"
        >
          <div class="flex justify-between items-start gap-2">
            <span class="font-semibold text-slate-800 shrink-0">#{{ job.job_number }}</span>
            <div class="flex items-center gap-1">
              <span
                v-if="job.is_urgent"
                class="text-[10px] font-bold text-red-600 bg-red-50 px-1.5 py-0.5 rounded"
              >
                URGENT
              </span>
              <span
                v-if="statusLabel(job.status)"
                class="text-[11px] font-medium text-right leading-tight"
                :style="{ color: statusColor(job.status) }"
              >
                {{ statusLabel(job.status) }}
              </span>
            </div>
          </div>
          <div class="text-slate-700 font-medium leading-tight mt-0.5 break-words">
            {{ job.name }}
          </div>
          <div class="text-slate-500 text-xs leading-tight">
            Company: {{ job.company_name || 'No Company' }}
          </div>
          <div class="text-slate-400 text-[11px] leading-tight">
            Rate: ${{ jobDisplayRate(job) }}/hr
          </div>
        </div>
      </div>
    </PopoverContent>
  </Popover>
</template>
